### ISSUE TITLE
Casting version strings to datatype [version] unreliable in Invoke-CMDownloadBiosPackage.ps1 

### ISSUE THREAD

**Issue by beanska** [SCConfigMgr/ConfigMgr#10]
When comparing versions in **Invoke-CMDownloadBiosPackage.ps1** the string is cast to the [version] datatype. Firmware versions often look like _"00.01.12 Rev A"_ so they are unable to be cast to [version]. I'll take a stab at using a version comparison function I have that may be more robust.

**Comment by maurice-daly** [comment]
Could you please advise the hardware platform you are using?

**Comment by beanska** [comment]
It was an Elitebook 840 G1. I tested on a different one I am not getting an error. I would say close the issue until I can repeat the issue and give you better information. Also I was pulling scripts from NickolajA/PowerShell rather than this repo. Thanks very much for your hard work.

**Comment by maurice-daly** [comment]
You might also check the update posted yesterday as it has improved logic.

________________________________
