### ISSUE TITLE
Invoke-DellBIOSUpdate vs WinPE 32-bits

### ISSUE THREAD

**Issue by timexy** [SCConfigMgr/ConfigMgr#100]
The current version of Invoke-DellBIOSUpdate.ps1 tries to use Flash64W.exe even if running a 32-bits version of WinPE.

There should be a check to confirm if the WinPE is either 32-bits or 64-its so it can use the correct executable to update the BIOS.

**Comment by NickolajA** [comment]
That's arguably true, but why are you using a 32-bit boot image?

**Comment by timexy** [comment]
Was my first time deploying an image through SCCM and I read somewhere that you needed 32-bit boot image for 32-bit OS on UEFI. Silly me didn't knew there's basically no 32-bit UEFI on newer computers.
