### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 Exit Code 9

### ISSUE THREAD

**Issue by ronmanp** [SCConfigMgr/ConfigMgr#105]
Hi, first of all thank you for this amazing tool. I'm just starting to use it so I'm probably missing something here. 

Here's my setup:
- Invoke-CMApplyDriverPackage.ps1 version 2.1.5
- Driver Automation Tool: 6.1.4
- Web Service: 1.7.0
- ConfigMgr 1806
- Package Name in: Drivers - Dell Precision 3930 Rack - Windows 10 x64
- Applying Windows 10 x64 1803 Ent image from WinPE 1803 x64
- Machine model: Dell Precision 3930 Rack
- Driver and script content distributed
- I'm running this command with PowerShell Execution Policy set to bypass. 
         Script: Invoke-CMApplyDriverPackage.ps1 
         Parameters: - URI "http://xxxxxxxxxxxxxx/ConfigMgrWebService/ConfigMgr.asmx" -SecretKey "xxxxxxxxxxxxxxxxxxxxxx" -Filter "Drivers" -DeploymentType BareMetal

Status Message from computer:
```
The task sequence execution engine failed executing the action (Dynamically Apply Drivers) in the group (Modern Driver Management) with the error code 9
Action output: ... .
In SSL, but with no client cert
In SSL, but with no media cert
Powershell path: X:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
ResolveSource flags: 0x00000000
SMSTSPersistContent: . The content for package EUR006F2 will be persistedLocations: Multicast = 0, HTTP = 1, SMB = 0.
Multicast is not enabled for the package.
Trying https://xxxxxxxxxxxxxxx/NOCERT_SMS_DP_SMSPKG$/EUR006F2.
WinHttp credentials set
In SSSL - but not using DP auth token or authenticator
In SSL, but withno client cert
List of files to be downloaded
Downloaded file from http://xxxxxxxxxxxxxxx:443/NOCERT_SMS_DP_SMSPKG$/EUR006F2/sccm?/Invoke-CMApplyDriverPackage.ps1 to C:\_SMSTaskSequence\Packages\EUR006F2\Invoke-CMApplyDriverPackage.ps1 
VerifyContentHash: Hash algorithm is 32780
Resolved source to 'C:\_SMSTaskSequence\Packages\EUR006F2'
Working dir 'C:\_SMSTaskSequence\Packages\EUR006F2'
Executing command line: Run Powershell script
Process completed with exit code 9
Command line returned 9. The operating system reported error 9: The storage control block address is invalid.
```

**Comment by NickolajA** [comment]
This is the proper error message that you're getting:

"Computer model detection logic failed for all detected driver packages"

Could you attach the ApplyDriverPackage.log from that device model?

**Comment by ronmanp** [comment]
Ok, just noticed that it thinks the image is Windows 7... I only have one package for this model and it's Windows 10 x64. 
Boot image is WinPE 1803 x64 and the image I'm applying is Windows 10 1803 x64.
Log file below: 

> <![LOG[===== SCConfigMgr Invoke-CMApplyDriverPackage Version 2.1.5 ====]LOG]!><time="18:24:30.517+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Driver download package process initiated]LOG]!><time="18:24:30.705+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Manufacturer determined as: Dell]LOG]!><time="18:24:30.955+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Computer model determined as: Precision 3930 Rack]LOG]!><time="18:24:30.955+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Computer SKU determined as: 0873]LOG]!><time="18:24:30.970+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Fallback SKU determined as: 0873]LOG]!><time="18:24:30.970+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Retrieved a total of 2 driver packages from web service]LOG]!><time="18:24:35.392+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Attempting to detect OS Image data from task sequence, running in DeploymentType: BareMetal]LOG]!><time="18:24:35.407+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Translated OSName from OSImageVersion: Windows 7]LOG]!><time="18:24:44.613+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Translated OSImageArchitecture: x64]LOG]!><time="18:24:44.613+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Using computer detection method: SystemSKU]LOG]!><time="18:24:44.644+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Attempting to find a match for driver package: Drivers - Dell Precision 3930 Rack - Windows 10 x64 (EUR006F1)]LOG]!><time="18:24:44.644+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Match found for computer model using detection method: SystemSKU and SKU value (0873)]LOG]!><time="18:24:44.863+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="1232" file="">
<![LOG[Driver package does not meet computer model, manufacturer and operating system and architecture criteria: Drivers - Dell Precision 3930 Rack - Windows 10 x64 (EUR006F1)]LOG]!><time="18:24:44.863+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="2" thread="1232" file="">
<![LOG[Computer model detection logic failed for all detected driver packages]LOG]!><time="18:24:44.879+0" date="03-29-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="2" thread="1232" file="">

**Comment by NickolajA** [comment]
I've actually never understood why it detects that as Windows 7 when it comes back from the web service. It's been reported before but I can't reproduce it unfortunately.

**Comment by NickolajA** [comment]
What if you run the methods manually that gets the image data from the web service?
