### ISSUE TITLE
Dell 7290 - wrong driver pacakge

### ISSUE THREAD

**Issue by hnewmanca** [SCConfigMgr/ConfigMgr#106]
I ran the script to pull the Dell Latitude 7290 drivers on Jan 10. It found a version A06, so I proceeded. Discovered that many of the drivers were missing. Went to the CAB site and found that the enterprise cab file for the 7290 is still on A02. There are 101 drivers in the A02 CAB file and only 46 in whatever SCConfigMgr pulled down.

Can I figure the script to ONLY look on the official CAB file page? It found it somewhere else.

**Comment by Alslinet** [comment]
Looks like i got a similar issue. When getting drivers for latitude 5175 which should be A09 its trying to download to a folder for dell latitude 5179 A10 Version. Is it somehow using the model below the one its supposed to on this page? https://www.dell.com/support/article/no/no/nobsdt1/sln312414/dell-command-deploy-driver-packs-for-enterprise-client-os-deployment?lang=en

**Comment by maurice-daly** [comment]
The driver and BIOS download links are provided by the OEM. I don't have control over these unfortunately.
