### ISSUE TITLE
Attempt to download and install drivers

### ISSUE THREAD

**Issue by misssunshine326** [SCConfigMgr/ConfigMgr#109]
Hello, any reason why the DestinationVariableName "OSDDriverPackage" is changed to "OSDDriverPackage01" for the variable $OSDDriverPackageLocation in line 778, 910, 1024.

Thanks in advance! :)

**Comment by NickolajA** [comment]
That's because the OSDDriverPackage variable is sort of an "array" type of variable, where you reference the first object in the "array" by adding 01.
