### ISSUE TITLE
[Feature Suggestion] Modern Driver Management. Extra Drivers to provision to all models

### ISSUE THREAD

**Issue by bachirica** [SCConfigMgr/ConfigMgr#110]
We're starting to use the whole Modern solution in our environment and we're very happy with the tests we've done in all scenarios (deployment, OS upgrade and driver upgrades)

But we miss something that I bet we're not the only ones doing... for example, when there are docking stations (or for some printers, scanners...) present in our customers environment, we provision to the machines the corresponding driver package for that model + an extra package with drivers for all that devices that they might connect at some point to their devices

I would be awesome that these kind of packages could be managed as custom packages in the automation tool and provisioned/upgraded through the script

Thanks!!
Bernardo

**Comment by NickolajA** [comment]
Hi, thank you for your feedback and suggestion for improvements. We'll take this into account when looking at adding new features in the future.
