### ISSUE TITLE
Drivers Pilot

### ISSUE THREAD

**Issue by snehalraob** [SCConfigMgr/ConfigMgr#111]
Hello @NickolajA @maurice-daly @JordanTheITGuy / Any one who have similar issue,

When a new version of driver is released, we are creating a Drivers Pilot package in SCCM. Challenge is that the newly created Drivers Pilot package is detected as matched driver for a model and being installed in production.

1. I tried changing the $Filter to "Drivers Pilot" and "Drivers -" , no luck still behaves as original script 
2. Also tried changing the -Filter in command line executing PowerShell to "Drivers -" and " Drivers Pilot" fails with error code 1.

Please suggest, thanks for helping me here.

**Comment by NickolajA** [comment]
Hi, yeah we're aware of this issue and are looking into a solution. Thank you for raising it with us though.

**Comment by NickolajA** [comment]
Just came up with a solution for this. We're adding the -OperationalMode parameter that takes the following values:
- Production
- Pilot

For a production scenario, don't specify this parameter on your command line. For a pilot scenario, add this new parameter with the value of 'Pilot' and it'll filter out all driver packages that doesn't match 'Pilot' in the package name from the results returned by the web service.

This will be released soon and available from version 2.2.1.
