### ISSUE TITLE
Problem with (very) old HP BIOS version using F.xx format

### ISSUE THREAD

**Issue by Ginolard** [SCConfigMgr/ConfigMgr#113]
So - much like the Dell versioning issue that has since been fixed I noticed today that the same problem occurs with some of our (very) old HP laptops.  For example, the 2570p model uses the F.xx versioning format.  Bloody annoying!

Anyway, I resolved this by adding a small check in the Compare-BIOSVersion function.  It splits the SMBIOSBIOSVersion string into two parts and does a regex on the first one to see if it's numeric.  A bit inelegant but it serves its purpose until we can get rid of these ancient beasts.
```

$RealCurrentBIOSVersion = $CurrentBIOSProperties.SMBIOSBIOSVersion
$BIOSMajorVersion=((($RealCurrentBIOSVersion).Trim($RealCurrentBIOSVersion.Split(".")[0])).TrimStart(".")).Trim().Split('.')[0]

# Detect new versus old BIOS formats
switch -wildcard ($($CurrentBIOSProperties.SMBIOSBIOSVersion)) {
	"*ver*" {
        #Handle really old BIOS version that use F.xx format
        If ($BIOSMajorVersion -match '^\d+$') {
            $CurrentBIOSVersion = [System.Version]::Parse(((($RealCurrentBIOSVersion).Trim($RealCurrentBIOSVersion.Split(".")[0])).TrimStart(".")).Trim())
        } Else {
            $AvailableBIOSVersion = $AvailableBIOSVersion.Split(".")[1]
            $CurrentBIOSVersion = ((($RealCurrentBIOSVersion).Trim($RealCurrentBIOSVersion.Split(".")[0])).TrimStart(".")).Trim().Split('.')[1]
        }
	}
	default {
		$CurrentBIOSVersion = "$($CurrentBIOSProperties.SystemBiosMajorVersion).$($CurrentBIOSProperties.SystemBiosMinorVersion)"
	}
}
```

**Comment by NickolajA** [comment]
Hey, from looking at the code only, it would seem that it'd always run the if condition code block since both F.XX and XX.XX.XX would always generate a numerical value.

**Comment by Ginolard** [comment]
But it doesn't because you are trying to strongly type F.xx as
[System.Version] and F.XX does not conform to that.  So the script always
fails with *Exception calling "Parse" with "1" argument(s): "Input string
was not in a correct format."*

I can bypass that by simply replacing F.x with 0.x but that's an ugly hack
;)

Matt

**Comment by NickolajA** [comment]
Could you provide the values from the "SystemBIOSMajorVersion" and "SystemBIOSMinorVersion" properties, please? I'd like to test an idea I have.

**Comment by Ginolard** [comment]
Hi Nicolaj

Here you go.  I was looking into leveraging those values as well but I
couldn't see how they relate to the F.XX version numbering HP used to use.
We mostly have this issue with some 2560p/2570p Elitebooks (and a few old
Probooks but I'm not so worried about those as they'll be phased out soon)

SMBIOSBIOSVersion              : 68ISB Ver. F.67
SMBIOSMajorVersion             : 2
SMBIOSMinorVersion             : 7
SoftwareElementID              : 68ISB Ver. F.67
SoftwareElementState           : 3
SystemBiosMajorVersion         : 15
SystemBiosMinorVersion         : 103

**Comment by NickolajA** [comment]
Thanks!

**Comment by NickolajA** [comment]
So the "Ver." is actually there in the BIOS version on those models too, that means that the first switch code block should be triggered and that will basically just trim away all the data.

**Comment by Ginolard** [comment]
Why don't you just split on "Ver."?  That way you'll get the version number
as the second element in the array

**Comment by NickolajA** [comment]
Cause .Split() only supports a single char however -split supports multiple. It's possible but I'm testing a slightly different approach.

**Comment by NickolajA** [comment]
I wonder though, could there potentially be several releases of F.67 where the major and minor versions differ? Or would a newer release or patched version of F.67 be F.68?

**Comment by Ginolard** [comment]
This is what I ended up doing for our environment.  It's not pretty and may
well break if they change their versioning numbering again

if ($ComputerManufacturer -match "Hewlett-Packard") {
# Obtain current BIOS release
$CurrentBIOSProperties = (Get-WmiObject -Class Win32_BIOS | Select-Object
-Property *)
# Update version formatting
$AvailableBIOSVersion = $AvailableBIOSVersion.TrimEnd(".")

# Detect new versus old BIOS formats
            switch -wildcard ($($CurrentBIOSProperties.SMBIOSBIOSVersion)) {
"*ver*" {
                    $RealCurrentBIOSVersion =
($CurrentBIOSProperties.SMBIOSBIOSVersion -split "Ver.")[1].Trim()
                    If ($RealCurrentBIOSVersion -like "*F.*") {
                        $AvailableBIOSVersion = "00." +
$AvailableBIOSVersion.Split(".")[1]
                        $CurrentBIOSVersion = "00." +
$RealCurrentBIOSVersion.Split(".")[1]
                    } Else {
                        $CurrentBIOSVersion = $RealCurrentBIOSVersion
                        #$CurrentBIOSVersion =
[System.Version]::Parse(((($CurrentBIOSProperties.SMBIOSBIOSVersion).Trim($CurrentBIOSProperties.SMBIOSBIOSVersion.Split(".")[0])).TrimStart(".")).Trim())
                    }

}
default {
$CurrentBIOSVersion =
"$($CurrentBIOSProperties.SystemBiosMajorVersion).$($CurrentBIOSProperties.SystemBiosMinorVersion)"
}
}

**Comment by NickolajA** [comment]
This is what I'm going with and seems to work in all scenarios if you have the following types of BIOS versioning:

68ISB Ver. F.67
XXX Ver. 01.06.03
XXX Ver. 02.22

```
# Detect new versus old BIOS formats
switch -wildcard ($($CurrentBIOSProperties.SMBIOSBIOSVersion)) {
    "*ver*" {
        if ($CurrentBIOSProperties.SMBIOSBIOSVersion -match '.F.\d+$') {
            $CurrentBIOSVersion = ($CurrentBIOSProperties.SMBIOSBIOSVersion -split "Ver.")[1].Trim()
            $BIOSVersionParseable = $false
        }
        else {
            $CurrentBIOSVersion = [System.Version]::Parse(($CurrentBIOSProperties.SMBIOSBIOSVersion).TrimStart($CurrentBIOSProperties.SMBIOSBIOSVersion.Split(".")[0]).TrimStart(".").Trim())
            $BIOSVersionParseable = $true
        }
    }
    default {
        $CurrentBIOSVersion = "$($CurrentBIOSProperties.SystemBiosMajorVersion).$($CurrentBIOSProperties.SystemBiosMinorVersion)"
        $BIOSVersionParseable = $true
    }
}

# Output version details
Write-CMLogEntry -Value "Current BIOS release detected as $($CurrentBIOSVersion)." -Severity 1
Write-CMLogEntry -Value "Available BIOS release detected as $($AvailableBIOSVersion)." -Severity 1

# Compare current BIOS release to available
switch ($BIOSVersionParseable) {
    $true {
        if ([System.Version]$AvailableBIOSVersion -gt [System.Version]$CurrentBIOSVersion) {
            # Write output to task sequence variable
            if ($DebugMode -ne $true) {
                $TSEnvironment.Value("NewBIOSAvailable") = $true
            }
            Write-CMLogEntry -Value "A new version of the BIOS has been detected. Current release $($CurrentBIOSVersion) will be replaced by $($AvailableBIOSVersion)." -Severity 1
        }
    }
    $false {
        if ([System.Int32]::Parse($AvailableBIOSVersion.TrimStart("F.")) -gt [System.Int32]::Parse($CurrentBIOSVersion.TrimStart("F."))) {
            # Write output to task sequence variable
            if ($DebugMode -ne $true) {
                $TSEnvironment.Value("NewBIOSAvailable") = $true
            }
            Write-CMLogEntry -Value "A new version of the BIOS has been detected. Current release $($CurrentBIOSVersion) will be replaced by $($AvailableBIOSVersion)." -Severity 1
        }
    }
}
```

**Comment by NickolajA** [comment]
Adressed this issue in version 2.0.9. Would you be kind and verify if it works?

**Comment by Ginolard** [comment]
Ah that looks better!  Thanks and great job!

Matt

**Comment by NickolajA** [comment]
Please re-open if the problem persists.

**Comment by Ginolard** [comment]
Hi

Another bug, big one this time, in 1.03

You test if $PasswordBin -ne $null in order to set the correct parameters.
Thing is, if you don't specify a path for $PasswordBin that statement
always evaluates to true (at least for me it does).  You could just remove
the -ne $null and just do If ($PasswordBin)

Matt

**Comment by Ginolard** [comment]
It's because an empty string is still a string so will never really be
$null.  $Null refers to a non-defined object which an empty string is not

**Comment by Ginolard** [comment]
Sorry - forgot to say this is in the Invoke-HPBIOSUpdate and the
Invoke-LenovoBIOSUPdate scripts.

**Comment by Ginolard** [comment]
Hi again,

Any chance you could update the Lenovo BIOS script to support the older
WinFlash/WinFlash64 method?  For example, the X230 model uses this

Regards,

Matt
