### ISSUE TITLE
Problems downloading Dell AIO drivers on non AIO systems.

### ISSUE THREAD

**Issue by damon5334** [SCConfigMgr/ConfigMgr#114]
I have some Dell Optiplex 9010 systems, we have driver packs for the 9010 as well as the 9010 AIO and because it sees a newer Optiplex 9010 AIO driver package it is downloading that instead.

The logs say that the SKU matches for both the 9010 package as well as the 9010 AIO package, which is strange since they are different.

Am I missing something?

**Comment by vorlon77** [comment]
There is a bug. The comparator needs to be -eq in the script, not -match.
There is the same issue with several other Dell models with overlapping
names.

I'll try and get to posting some suggestions.

Allan.

**Comment by kenifyable** [comment]
Is this related to why I'm getting 5250 drivers on an E5250 device?

**Comment by vorlon77** [comment]
Probably.  And it would be the same for all of the other Dell models where
one model name is a substring of the other model name.

Allan.

**Comment by vorlon77** [comment]
The same issue exists for BIOS packages.  The change for Invoke-CMDownloadBIOSPackage.ps1 would be to change from:

					# Computer detection method matching
					$ComputerDetectionResult = $false
					switch ($ComputerManufacturer) {
						"Hewlett-Packard" {
							$PackageNameComputerModel = $Package.PackageName.Replace("Hewlett-Packard", "HP").Split("-").Trim()[1]
						}
						Default {
							$PackageNameComputerModel = $Package.PackageName.Split("-").Replace($ComputerManufacturer, "").Trim()[1]
						}
					}
					switch ($ComputerDetectionMethod) {
						"ComputerModel" {
							if ($PackageNameComputerModel -match $ComputerModel) {
								Write-CMLogEntry -Value "Match found for computer model using detection method: $($ComputerDetectionMethod) ($($ComputerModel))" -Severity 1
								$ComputerDetectionResult = $true
							}
						}
						"SystemSKU" {
							if ($Package.PackageDescription -match $SystemSKU) {
								Write-CMLogEntry -Value "Match found for computer model using detection method: $($ComputerDetectionMethod) ($($SystemSKU))" -Severity 1
								$ComputerDetectionResult = $true
							}
							else {
								Write-CMLogEntry -Value "Unable to match computer model using detection method: $($ComputerDetectionMethod) ($($SystemSKU))" -Severity 2
								if ($PackageNameComputerModel -match $ComputerModel) {
									Write-CMLogEntry -Value "Fallback from SystemSKU match found for computer model instead using detection method: $($ComputerDetectionMethod) ($($ComputerModel))" -Severity 1
									$ComputerDetectionResult = $true
								}
							}
						}
					}

to:

					# Computer detection method matching
					$ComputerDetectionResult = $false
					switch ($ComputerManufacturer) {
						"Hewlett-Packard" {
							$PackageNameComputerModel = $Package.PackageName.Replace("Hewlett-Packard", "HP").Split("-").Trim()[1]
						}
						Default {
							$PackageNameComputerModel = $Package.PackageName.Split("-",2).Replace($ComputerManufacturer, "").Trim()[1]
						}
					}
					switch ($ComputerDetectionMethod) {
						"ComputerModel" {
							if ($PackageNameComputerModel -eq $ComputerModel) {
								Write-CMLogEntry -Value "Match found for computer model using detection method: $($ComputerDetectionMethod) ($($ComputerModel))" -Severity 1
								$ComputerDetectionResult = $true
							}
						}
						"SystemSKU" {
							if ($Package.PackageDescription -match $SystemSKU) {
								Write-CMLogEntry -Value "Match found for computer model using detection method: $($ComputerDetectionMethod) ($($SystemSKU))" -Severity 1
								$ComputerDetectionResult = $true
							}
							else {
								Write-CMLogEntry -Value "Unable to match computer model using detection method: $($ComputerDetectionMethod) ($($SystemSKU))" -Severity 2
								if ($PackageNameComputerModel -eq $ComputerModel) {
									Write-CMLogEntry -Value "Fallback from SystemSKU match found for computer model instead using detection method: $($ComputerDetectionMethod) ($($ComputerModel))" -Severity 1
									$ComputerDetectionResult = $true
								}
							}
						}
					}

**Comment by NickolajA** [comment]
Should be fixed in both scripts now. Would be appreciated if anyone could verify.
