### ISSUE TITLE
Password problem with Invoke-LenovoBIOSUpdate

### ISSUE THREAD

**Issue by My-userid** [SCConfigMgr/ConfigMgr#115]
I'm trying to use this in my TS, but get a weird error.
I don't use password for BIOS, and don't enter one, but get this in the log filer:

`<![LOG[Using the following switches for BIOS file: <Password Removed> <Password Removed>/<Password Removed>q<Password Removed>u<Password Removed>i<Password Removed>e<Password Removed>t<Password Removed> <Password Removed>/<Password Removed>s<Password Removed>c<Password Removed>c<Password Removed>m<Password Removed> <Password Removed>/<Password Removed>i<Password Removed>g<Password Removed>n<Password Removed> <Password Removed>/<Password Removed>p<Password Removed>a<Password Removed>s<Password Removed>s<Password Removed>:<Password Removed>]LOG]!><time="15:24:11.193+-480" date="03-22-2019" component="LenovoBIOSUpdate.log" context="NT AUTHORITY\SYSTEM" type="1" thread="1544" file="">`

Somehow $Password gets set to some weird value, and then wants to apply the /pass parameter, but then the BIOS update fails.

For now I just removed the password parameter in the script, as I don't use it.

**Comment by NickolajA** [comment]
Could you please verify if it works in the latest update to the script?
