### ISSUE TITLE
Invoke-CMDownloadBIOSPackage.ps1 Some Dell models have spaces at the end of the model name in BIOS

### ISSUE THREAD

**Issue by vorlon77** [SCConfigMgr/ConfigMgr#123]
Some Dell models with some BIOS versions have trailing spaces at the end of the model name.  Invoke-CMDownloadBIOSPackage.ps1 function Compare-BIOSVersion change:

$ComputerModel = Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model

to

$ComputerModel = (Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model).Trim()

**Comment by NickolajA** [comment]
This will get fixed shortly in the next version and updated with the same logic from Invoke-CMApplyDriverPackage.ps1 script.
