### ISSUE TITLE
Invoke-CMDownloadBIOSPackage.ps1 incorrectly determines the model covered by a BIOS package if the model name contains - characters

### ISSUE THREAD

**Issue by vorlon77** [SCConfigMgr/ConfigMgr#124]
There is a problem in Invoke-CMDownloadBIOSPackage.ps1 when the model names contain - characters.  Models affected include the Dell "Latitude 3390 2-in-1" "Latitude 5290 2-in-1" "Latitude E5430 non-vPro".  This issue should also affect the equivalent file that downloads drivers.

	$PackageNameComputerModel = $Package.PackageName.Split("-").Replace($ComputerManufacturer, "").Trim()[1]

should be changed to 

	$PackageNameComputerModel = $Package.PackageName.Split("-",2).Replace($ComputerManufacturer, "").Trim()[1]

**Comment by NickolajA** [comment]
Fixed in Invoke-CMDownloadBIOSPackage.ps1 version 2.1.1. Invoke-CMApplyDriverPackage.ps1 2.2.2, which is recently released does not contain this issue.
