### ISSUE TITLE
Invoke-DellBIOSUpdate.ps1 ignores model checks when flashing BIOS

### ISSUE THREAD

**Issue by vorlon77** [SCConfigMgr/ConfigMgr#125]
Invoke-DellBIOSUpdate.ps1 uses the /f switch to override the model checks to force the installation of a BIOS version even if the model of the BIOS update doesn't match.  This is not desirable and could initially be caused a bug in the download code or a problem with Dell's site.  (If you happen to flash a E7250 with the bios for a 7250 you can end up with a laptop with a black screen.)  I'd propose making this safer by changing:

	$FlashSwitches = "/b=$($CurrentBIOSFile) /s /f /l=$($BIOSLogFile)"

to

	$FlashSwitches = "/b=$($CurrentBIOSFile) /s /l=$($BIOSLogFile)"

**Comment by NickolajA** [comment]
Appreciate your feedback and I agree, especially with the differences between E-models and the non-E models. Fixed in 1.0.9.
