### ISSUE TITLE
Invoke-LenovoBIOSUpdate.ps1 fails if no winuptp.log is generated

### ISSUE THREAD

**Issue by SeanCoB** [SCConfigMgr/ConfigMgr#126]
The Invoke-LenovoBIOSUpdate.log file will show:

winuptp.log file patch is
An error occurred while updating the system BIOS in OS online phase. Error message: Cannot bind argument to parameter 'Path' because it is null.

**Comment by NickolajA** [comment]
Would you be kind and verify if the fix in 1.0.8 has solved this issue?

**Comment by SeanCoB** [comment]
Yes it does. Thank you Nickolaj!
