### ISSUE TITLE
Issue with DebugMode

### ISSUE THREAD

**Issue by PhilDyer94** [SCConfigMgr/ConfigMgr#127]
Can't run the script correctly with the DebugMode switch, it correctly prompts me for a TSPackageID but no matter what I enter there it gives me the error "Unable to construct Microsoft.SMS.TSEnvironment object"

Might be a layer 8 issue but can't find any other documentation regarding debug mode.

**Comment by NickolajA** [comment]
This will be fixed in 2.2.2 that will be released shortly.
