### ISSUE TITLE
Error when updating HP BIOS

### ISSUE THREAD

**Issue by trev2000** [SCConfigMgr/ConfigMgr#129]
Hi 
Im getting the following error when trying to update HP BIOS on various models both as a bare metal build and withing the OS. I believe i have followed the guide correct my task sequence steps are as follows
![image](https://user-images.githubusercontent.com/49308224/55622848-3e661100-5799-11e9-90d1-622ac2747fb7.png)

Parameters 
1st step of the task sequence is as follows
![image](https://user-images.githubusercontent.com/49308224/55622942-82591600-5799-11e9-987f-fda039058490.png)

2nd Step of the TS is
![image](https://user-images.githubusercontent.com/49308224/55622991-9d2b8a80-5799-11e9-98e2-3436d8937db3.png)

The error in the task sequence log is as follows
![image](https://user-images.githubusercontent.com/49308224/55623055-bdf3e000-5799-11e9-9142-b08ed22c3b78.png)

Believe the above is all correct any guidance or suggestions to try would be appreciated.
We only have HP models so unable to test on other devices

Many thank is advance

**Comment by 10Toes** [comment]
Mine dies at the same place yours is but is only happening with the HP 800 series 35w Desktop Mini PC.  All are other HP models are updating the BIOS without an issue.  I'm using 2.0.7 Invoke-CMDownloadBIOSPackage.ps1 and 1.7.0 ConfigMgr WebService.

**Comment by Ginolard** [comment]
I think this might be caused by the fact that some older models (in our case 2570p) do not use the HPBIOSUPDREC.exe.  Instead they still use HPQFLASH.  

The BIOS Update script expects to find HPBIOSUPDREC/HPBIOSUPDREC64 executable

**Comment by 10Toes** [comment]
The model machine I'm having an issue with uses the HPBIOSUPDREC/64.exe.  
The ApplyBIOSPackage.log ends here

![image](https://user-images.githubusercontent.com/50030385/56899428-08931000-6a59-11e9-90a7-e671383cc5b8.png)

It will normally have all the info on what version it will be flashing with after that line.

![image](https://user-images.githubusercontent.com/50030385/56899667-a1299000-6a59-11e9-809c-d87a26b1be64.png)

**Comment by Ginolard** [comment]
Yeah, looks like you are having the same issue that I've been having.  It
doesn't parse the version number of the BIOS correctly.  I'm not sure why
he chose to do it the way he did.  I modified the script to make work for
us.  Maybe it will work for you.

In the Invoke-CMDownloadBIOSPackage script, you need to replace the entire
Switch statement in the Compare-BIOSVersion function with this.

You can see I've added some logic to handle the REALLY old HP BIOS
versioning that used the F.XX format (yeah - we have some VERY old
laptops....)

            switch -wildcard ($($CurrentBIOSProperties.SMBIOSBIOSVersion)) {
"*ver*" {
                    $RealCurrentBIOSVersion =
($CurrentBIOSProperties.SMBIOSBIOSVersion -split "Ver.")[1].Trim()
                    If ($RealCurrentBIOSVersion -like "*F.*") {
                        $AvailableBIOSVersion = "00." +
$AvailableBIOSVersion.Split(".")[1]
                        $CurrentBIOSVersion = "00." +
$RealCurrentBIOSVersion.Split(".")[1]
                    } Else {
                        $CurrentBIOSVersion = $RealCurrentBIOSVersion

                    }

}
default {
$CurrentBIOSVersion =
"$($CurrentBIOSProperties.SystemBiosMajorVersion).$($CurrentBIOSProperties.SystemBiosMinorVersion)"
}
}

**Comment by fl4tout** [comment]
Having the exact same issue here as well.

**Comment by NickolajA** [comment]
Invoke-HPBIOSUpdate.ps1 now has a fix for the HPQFlash.exe and HPQFlash64.exe. As for the BIOS version matching, let me get back about that.

**Comment by NickolajA** [comment]
We've asked HP for a full list of possible BIOS version standards and will update the script in order to support them all once we know what to look for.

**Comment by NickolajA** [comment]
See fix from this issue that will be implemented in an upcoming version. #113
