### ISSUE TITLE
downloading wrong bios package regarding optiplex 9020 and 9020m

### ISSUE THREAD

**Issue by vartaxe** [SCConfigMgr/ConfigMgr#142]
hi,
i think there is a situation here:
``***BIOS flash finished at 5/22/2019 at 19:00:56***
***BIOS flash started on 5/22/2019 at 19:00:56***
Command: C:\_SMSTaskSequence\BIOSPackage\TIC00579\Flash64W.exe /b=C:\_SMSTaskSequence\BIOSPackage\TIC00579\9020MA18.exe /s /l=C:\WINDOWS\CCM\Logs\SMSTSLog\DellFlashBIOSUpdate.log
A12 INSTALLED (Dell System OptiPlex 9020)
- Gigabit Ethernet : 0.D.4
- System BIOS : A12
- Legacy RAID OROM : 12.7.0.1936
- Intel Management Engine Update : 9.1.20.1035
A18 UPDATE (Dell System OptiPlex 9020M)
- System BIOS : A18
- Gigabit Ethernet : 0.D.4
- Legacy Video OROM : 1.0.2.5
- Legacy RAID OROM : 12.0.0.1710
- Intel Management Engine Update : 9.1.45.3000
- ACPI OS support : 5.0.0.0
Error: Unsupported System ID Found.
Cannot update a 'OptiPlex 9020' with a BIOS for 'OptiPlex 9020M'.
Exit Code = 5 (Hard Qualification Error)

**Comment by vartaxe** [comment]
its downloading the correct driver package so this is limited to download bios package

**Comment by vartaxe** [comment]
Who can fix this?

**Comment by EvilerBetty** [comment]
I had the same problem with the Latitude E5450 (A19 I think) BIOS.  The BIOS for the Latitude 5450 was installing (successfully with DOA board consequences) on the Latitude E5450.

I opened a case with Dell and they pulled / corrected the metadata for the E5450 BIOS download.
