### ISSUE TITLE
Lenovo M93 Computer model detection logic failed for all detected driver packages

### ISSUE THREAD

**Issue by kasparssc** [SCConfigMgr/ConfigMgr#145]
Hi. I am trying to implement MDM and having problem to do Lenovo ThinkCentre M93p  (10A6-S1PK00) Windows 10 1809 baremetal OSD. TS stops with error 9. 
Call to web service for package objects returned empty.
What I am doing wrong?

===== SCConfigMgr Invoke-CMApplyDriverPackage Version 2.2.3 ====	ApplyDriverPackage	29.05.2019 11:41:50	2024 (0x07E8)
Driver download package process initiated	ApplyDriverPackage	29.05.2019 11:41:50	2024 (0x07E8)
Manufacturer determined as: Lenovo	ApplyDriverPackage	29.05.2019 11:41:51	2024 (0x07E8)
Computer model determined as: **ThinkCentre M93p**	ApplyDriverPackage	29.05.2019 11:41:51	2024 (0x07E8)
Computer **SKU determined as: 10A6**	ApplyDriverPackage	29.05.2019 11:41:51	2024 (0x07E8)
Retrieved a total of 19 driver packages from web service	ApplyDriverPackage	29.05.2019 11:42:01	2024 (0x07E8)
Attempting to detect OS Image data from task sequence, running in DeploymentType: BareMetal	ApplyDriverPackage	29.05.2019 11:42:01	2024 (0x07E8)
Translated OSName from OSImageVersion: Windows 10	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Translated OSVersion from OSImageVersion: 1809	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Translated OSImageArchitecture: x64	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Using computer detection method: SystemSKU	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Attempting to find a match for driver package: Drivers - Lenovo ThinkCentre M900 - Windows 10 x64 (IT100160)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Unable to match computer model using detection method: SystemSKU (10A6)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Driver package does not meet computer model, manufacturer and operating system and architecture criteria: Drivers - Lenovo ThinkCentre M900 - Windows 10 x64 (IT100160)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
**Attempting to find a match for driver package: Drivers - Lenovo ThinkCentre M93p - Windows 10 x64 (IT100163)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Unable to match computer model using detection method: SystemSKU (10A6)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Fallback from SystemSKU match found for computer model instead using detection method: SystemSKU (ThinkCentre M93p)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)
Driver package does not meet computer model, manufacturer and operating system and architecture criteria: Drivers - Lenovo ThinkCentre M93p - Windows 10 x64 (IT100163)	ApplyDriverPackage	29.05.2019 11:42:05	2024 (0x07E8)**

from smsts.log
Downloading file /SMS_DP_SMSPKG$/IT100179/sccm?/Invoke-CMApplyDriverPackage.ps1 range 0-66511	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Downloaded file from http://server.domain.com:80/SMS_DP_SMSPKG$/IT100179/sccm?/Invoke-CMApplyDriverPackage.ps1 to C:\_SMSTaskSequence\Packages\IT100179\Invoke-CMApplyDriverPackage.ps1 	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
VerifyContentHash: Hash algorithm is 32780	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Content successfully downloaded at C:\_SMSTaskSequence\Packages\IT100179.	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Resolved source to 'C:\_SMSTaskSequence\Packages\IT100179'	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Working dir 'C:\_SMSTaskSequence\Packages\IT100179'	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Command line for extension .exe is "%1" %*	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Set command line: Run PowerShell Script	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
PowerShell command line is NOT shown in the log ('OSDLogPowerShellParameters' is NOT set to 'True')	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Executing command line: Run PowerShell Script with options (0, 4)	RunPowerShellScript	29.05.2019 11:41:42	1604 (0x0644)
Process completed with exit code 9	RunPowerShellScript	29.05.2019 11:42:06	1604 (0x0644)
PowerShell command line returned code 9	RunPowerShellScript	29.05.2019 11:42:06	1604 (0x0644)
ReleaseSource() for C:\_SMSTaskSequence\Packages\IT100179.	RunPowerShellScript	29.05.2019 11:42:06	1604 (0x0644)
reference count 1 for the source C:\_SMSTaskSequence\Packages\IT100179 before releasing	RunPowerShellScript	29.05.2019 11:42:06	1604 (0x0644)
Released the resolved source C:\_SMSTaskSequence\Packages\IT100179	RunPowerShellScript	29.05.2019 11:42:06	1604 (0x0644)
Process completed with exit code 9	TSManager	29.05.2019 11:42:06	1800 (0x0708)
![image](https://user-images.githubusercontent.com/51155538/58545290-9ce4c400-820b-11e9-88fe-fa10a743159d.png)

**Comment by Jtracy-ItPro** [comment]
The models in the M93p package are actually the M93p TINY.
Your model is a 10A6, that's a M93p MINI TOWER. I also have this PC but it's a 10A7.

You might have to make your own package. I will probably use the fallback package because we only have a few of these PCs and they're all being used by IT staff.

**Comment by kasparssc** [comment]
Thanks. How to call that package? Because we have them a lot.

**Comment by Jtracy-ItPro** [comment]
The Fallback package? Use the driver automation tool to create it. Then read the Invoke-CMApplyDriverPackage.ps1 file. It describes the -UseDriverFallback parameter.

**Comment by kasparssc** [comment]
Hi. No . I thought how to name M93p 10A6 package. I do not want to use fallback if it is possible.

**Comment by Jtracy-ItPro** [comment]
If you were so inclined, you could edit the comment of the m93p package so it has 10a6 in the list, but I think this package is for the wrong model anyway. The m93p tower is different from the tiny, so it could need different drivers. Easy example - the mini tower might come with a geforce or radeon , but the Tiny wouldn't have drivers for that.
