### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1  Error : line 476 243

### ISSUE THREAD

**Issue by TonyDewhurst** [SCConfigMgr/ConfigMgr#15]
At C:\_SMSTaskSequence\Packages\EU200063\Invoke-CMApplyDriverPackage.ps1:476 char:243	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
+ ... h $OSName) -and ($Package.PackageName -match $OSImageArchitecture)) {	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
+                                                                         ~	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
Unexpected token '{' in expression or statement.	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
At C:\_SMSTaskSequence\Packages\EU200063\Invoke-CMApplyDriverPackage.ps1:476 char:243	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
+ ... h $OSName) -and ($Package.PackageName -match $OSImageArchitecture)) {	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
+                                                                         ~	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
Missing closing ')' after expression in 'if' statement.	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
    + CategoryInfo          : ParserError: (:) [], ParseException	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
    + FullyQualifiedErrorId : UnexpectedToken	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)
 	RunPowerShellScript	19/01/2018 23:15:06	1132 (0x046C)

**Comment by NickolajA** [comment]
Should be fixed now.

**Comment by TonyDewhurst** [comment]
Many Thanks x
