### ISSUE TITLE
Webservice 1.7.0 : ImportCMComputerByMacAddress broken?

### ISSUE THREAD

**Issue by MaartenPauchet** [SCConfigMgr/ConfigMgr#151]
When trying to import a new device using ImportCMComputerByMacAddress the device is not being created. 

`$Invocation = $WebService.ImportCMComputerByMacAddress( $SecretKey,'11:22:33:44:55:66','XXYYY1234')`

I checked the eventlog which talks about a problem logged by smsprovider.
So I checked SMSPROV.LOG and noticed an error that the MAC address provided through the webservice is not in the right format. 
I tried different formats
11:22:33:44:55:66
112233445566
11-22-33-44-55-66
but the error is always the same.

when doing a manual import through the console the smsprog logs the mac in the format 11:22:33:44:55:66 so my assumption is that this is the correct format. 

I've check the rights of the account that is being used by the webservice and even gave it temporary Operational admin just for testing. did not make a difference. 
Attached the snipped of the smsprov.log for your reference
<img width="361" alt="smsprov-importpc" src="https://user-images.githubusercontent.com/12744314/59147616-3f682880-89fe-11e9-8b1b-6d39c34de80d.png">

**Comment by MaartenPauchet** [comment]
HA! found it just now by looking back at the log... 
the function works but the documentation has the parameters in the wrong order. 
its ImportCMComputerByMacAddress( $SecretKey,$ComputerName,$MAC)!

**Comment by NickolajA** [comment]
This will be addressed in the 1.8.0 update of the docs.
