### ISSUE TITLE
Invoke-CMApplyDriverPackage: Fallback package only works on known vendors - We need Acer!

### ISSUE THREAD

**Issue by Jtracy-ItPro** [SCConfigMgr/ConfigMgr#153]
If I try to run the script on an oddball PC like Acer, Asus or AsRock, I expect the fallback package to load with -UseDriverFallback. It always works when I have a weird Lenovo, for example. But the log says:

Unable to determine system SKU value
Computer model and SystemSKU values are either null or empty strings
etc...

Then it loads no package at all.

If you look at the switch statement at line #545, it never fills the model SKU values unless it recognizes the OEM. So it never tries to load any package.

It would be nice if the switch statement had a default code block that just allows the package loading routines to run for -UseDriverFallback.

=-=-=-=-
here's some info on a gamer-class Acer laptop, for what it's worth...
=-=-=-

PS C:\WINDOWS\system32> gwmi -ComputerName xxxxx win32_computersystem |select manufacturer,model,systemskunumber,oemstringarray |fl

manufacturer    : Acer
model           : Aspire VN7-791
systemskunumber : Aspire VN7-791_091D_1.11
oemstringarray  : {Acer System}

PS C:\WINDOWS\system32> gwmi -ComputerName xxxxx win32_computersystemproduct |select vendor,name |fl

vendor : Acer
name   : Aspire VN7-791

**Comment by Jtracy-ItPro** [comment]
At the present time, I have made a separate "override" TS step block, that loads a DriverPackageId assigned to that model in CustomSettings.Ini.

But I was already using this mechanism before using the ScConfigMgr solution - I would rather not use both.

**Comment by vartaxe** [comment]
We have the same issue 95% from our 4000devices are mostly dell with a few hp and lenovo but sometimes there are some other unknown brands show up for whatever reason so yes being able to use a generic fallback package would be the solution for those
