### ISSUE TITLE
GetCMOSImageForTaskSequence Error

### ISSUE THREAD

**Issue by BlairKingsley** [SCConfigMgr/ConfigMgr#156]
I have discovered that the web service method **GetCMOSImageForTaskSequence** fails if you use the option **Apply operating system from an original installation source** in a task sequence under the **Apply Operating System** action. Error from web service is **Object reference not set to an instance of an object.** If you use the option **Apply operating system from a captured image** it works okay. Deployment type is BareMetal. Invoke-CMApplyDriverPackage version 2.1.2. Web Service version 1.6.0.

**Comment by BlairKingsley** [comment]
![TSOption](https://user-images.githubusercontent.com/46717232/60966832-14306c00-a311-11e9-9efb-972111d51855.jpg)

**Comment by BlairKingsley** [comment]
Current workaround is to have a disabled action which uses the **Apply operating system from a captured image** option with a matching OS version.

**Comment by BlairKingsley** [comment]
Issue breaks Invoke-CMApplyDriverPackage.ps1 process. As when the web service call fails the script exits with error code 3.

**Comment by capnjax21** [comment]
I am having the same issue. Running WebService 1.8 - ConfigMgr 1806
