### ISSUE TITLE
Issue with HPQFlash -s -r switch and HP ProBook 4510s

### ISSUE THREAD

**Issue by Stuart42** [SCConfigMgr/ConfigMgr#157]
Using version 1.0.0.5 of the Invoke-HPBIOSUpdate.ps1 script, we've been seeing issues applying the update using the -s -r switch. Changing it to use -s instead appears to work correctly.

The error from the HPQFlash log is below:

`2019/07/11 14:54:11.284|00001A44|Information|ChpqFlashApp::InitInstance|--- START NEW HPQFLASH SESSION, HPQFLASH version 4.40.4.1 ---
2019/07/11 14:54:11.315|00001A44|Information|ChpqFlashApp::CPQFProcessCmdLineArgs|Command line = -s -r
2019/07/11 14:54:11.337|00001A44|Information|CPQMessageBox|Error Code  0x00000115  INVALID_CMDLINE_PARAMETERS
2019/07/11 14:54:11.354|00001A44|Information|ChpqFlashApp::ExitInstance|Exit hpqFlash:  Return Code = 0x103
`

**Comment by NickolajA** [comment]
Thank you for the info, we'll look into this and update the script.
