### ISSUE TITLE
DATSettings.xml Ignored

### ISSUE THREAD

**Issue by Bennyocb** [SCConfigMgr/ConfigMgr#160]
Not sure if this is a common issue but the configuration in DATSettings.xml is being ignored every time I open the GUI version of the tool. I'm not sure if there is another cache somewhere of selected models that I'm missing but I can't see how else that I'm getting a tonne of additional models selected whenever I go to run the tool.

I've raised a separate issue relating to automating running the tool via silent operation but I'm concerned that once I've managed to get it automated, it will have all these additional models selected that I don't want.

**Comment by merlinfrombelgium** [comment]
Have you recently updated to version 6.2? Reason I ask is that version is now installed to Program Files and you might end up with two locations for your DAT. I'd recommend looking at Task Manager or Get-Process and check out the command line. Download and use ProcMon to make sure the DATSettings file is read from where you expect it to be. As do you, I'm guessing there's a second settings file.

**Comment by Bennyocb** [comment]
Thanks for the reply.

This is a fresh install so not upgraded. Also, within the process log, the initialisation shows the settings file location as C:\Program Files\SCConfigMgr\Driver Automation Tool\Settings - which is the same directory as the DATSettings.xml I'm looking at.

Even if I have it open in Notepad++, edited with the models listed that I want and also have the DAT GUI open with the correct models selected and then close the GUI, Notepad++ prompts that the xml file has been modified - when I reload it, a bunch of additional models are added and the order screwed up.

**Comment by merlinfrombelgium** [comment]
Have you selected the option 'Select Known Models'?
Care to share your DATSettings.xml file? You can PM me or redact the file to obfuscate names.

**Comment by Bennyocb** [comment]
[DATSettings.zip](https://github.com/SCConfigMgr/ConfigMgr/files/3410207/DATSettings.zip)

Hi Merlin, thanks again for your reply.

I can't find any option within the GUI nor the DATSettings xml for 'Select Known Models' (nothing in the guide for this). I've attached a zip file with 2 XMLs, one with the models I want (correct) and the one DAT is modifying after it's closed (incorrect).

Let me know if you find anything. Appreciate it.

**Comment by Bennyocb** [comment]
Closed as deselecting 'Select Known Models' under the ConfigMgr Site Server / Storage Locations tab fixed the issue. Also upgraded to 6.3.1, but doubt this was the fix.
