### ISSUE TITLE
'Remove Driver Source Packages' Not Working

### ISSUE THREAD

**Issue by Bennyocb** [SCConfigMgr/ConfigMgr#161]
I have the 'Remove Driver Source Packages' option selected under the Driver Cleanup section - at the end of running the tool, the process log shows 'ConfigMgr: Removing driver download and extracted source driver files from \\xyz' but the source files are still present so it appears the option is not deleting them, as expected.

**Comment by vartaxe** [comment]
I confirm this behavior
