### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 update existing computer

### ISSUE THREAD

**Issue by MarcelRond** [SCConfigMgr/ConfigMgr#167]
Hello Thanks for all the work you put in this tool!
env:
SCCM ver: 1902
Invoke-CMApplyDriverPackage.ps1 ver: 2.2.3
Webservice: 1.8.0

I am testing to see if I can use the script with SCCM to update existing Win10 computers with drivers. I couldn't find how to implement the script in a TS with the "-DeploymentType DriverUpdate" option.
To do some testing I created a new empty TS and deployed it to a Server 2016 VM, just to see If the script works. I would expect the script to not find a match for drivers, and log accordingly.
When I run the TS from Software Center I get an error that the TS fails.

I get errors in the smsts.log logfile:
- Process completed with exit code 10
- Failed to run the action: Dynamically Apply Drivers. The environment is incorrect. (Error: 0000000A; Source: Windows)
No other logs are created. 

I tried this:
Create a new empty TS and only put in the Powershell Script with command:
script name: _Invoke-CMApplyDriverPackage.ps1__ 
Parameters: _-URI "http:/<servername>/ConfigMgrWebService/ConfigMgr.asmx" -SecretKey "<key>" -Filter "Drivers" -DeploymentType DriverUpdate_
PS policy is set to "Bypass"
Then I run the TS from the booted Win2016 Server (it is displayed in Software Center)

What am I doing wrong? Probably missing something by mistake. Sorry for that.

**Comment by EvilerBetty** [comment]
How I have it configured:

![image](https://user-images.githubusercontent.com/17093431/61888162-ae271580-aec8-11e9-859a-c7d4f15adec6.png)

**Comment by EvilerBetty** [comment]
How I have it configured:

![image](https://user-images.githubusercontent.com/17093431/61888266-d57de280-aec8-11e9-8454-401377219059.png)

**Comment by NickolajA** [comment]
You need to use the OSUpgrade parameter input value for DeploymentType parameter when upgrading Windows 10 builds.

**Comment by NickolajA** [comment]
Sorry, completely misread your comment.

**Comment by NickolajA** [comment]
If I'm reading it correctly this time, doh, the script won't run since it has detected that you're running on a VM and it's bailing out. We currently don't support VMs, you'd have to try with a physical machine.

**Comment by MarcelRond** [comment]
Thanks for the responses. I’ll try on hardware device and also add the bios update.
