### ISSUE TITLE
Driver Automation Tool 6.3.0 - Pilot Package / Mange to Prod

### ISSUE THREAD

**Issue by EvilerBetty** [SCConfigMgr/ConfigMgr#169]
Attempting to download driver / BIOS packages as "Pilot" packages to prevent the TS from trying to use packages that haven't been distributed yet.  This works, but subsequent checks for updated packages results in package duplicates, if Deployment State changed through Package Management.

1. Select Deployment Platform: "ConfigMgr - Standard Pkg (Pilot)"
2. Download packages.
3. Change Deployment state to "Production".
4. Download packages again.
5. Packages that were previously downloaded as pilot and renamed, are duplicated so that you now have packages of the same version as both production and pilot.

If you download them as non-Pilot drivers, manage them to pilot after download, then switch them back to Production after distribution, this issue does not occur, but due to how long it takes to distribute content to remote locations, this isn't a good workaround for us.

**Comment by maurice-daly** [comment]
Code added into the next release will check for Pilot versions of the same version. If this is detected, you will be notified in the log that you need to promote this package to production.

Expect in the next 4.6.7 release in approx 2-3 weeks (waiting on an update from an OEM)
