### ISSUE TITLE
DAT Latitude 5590 bios

### ISSUE THREAD

**Issue by vartaxe** [SCConfigMgr/ConfigMgr#171]
Driver automation tool thinks latest available bios for latitude 5590 is 1.9.0 but if we go to the support page at dell we will actually find the latest version available is already 1.10.1 so i think this is due to using the dell catalog cab file which by design probably has some delays or require manual update from dell guys and so i was wondering if maybe some kind of html scrapper could be done to search through the site like i think is already done for the drivers?

**Comment by EvilerBetty** [comment]
The Driver CABs are fetched from a catalog that mirrors:  https://www.dell.com/support/article/us/en/04/sln312414/dell-command-deploy-driver-packs-for-enterprise-client-os-deployment?lang=en

The BIOS files are fetched (I believe) from ftp.dell.com:  http://download.dell.com/published/pages/latitude-15-5590-laptop.html

These are the updates Dell has blessed as ready for Enterprise use.

Drivers on the other support pages are general release, and haven't been necessarily vetted for enterprise use.

**Comment by vartaxe** [comment]
Ok so this confirms my toughts
