### ISSUE TITLE
Unable to detect current OS name from TS reference objects

### ISSUE THREAD

**Issue by NickPifer86** [SCConfigMgr/ConfigMgr#18]
I'm working on setting this up in my environment, but running into this error. I'm using the current code through today. Am I missing something in my implementation? It appears the web service is flagging my dell latitude 3480 as a windows server 2012 machine (according to the OSImageVersion retrieved from the web service in the log). My image is windows 10 1703 (build 15063.674).

[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1657791/ApplyDriverPackage.log)

Thank you for making this tool available!

**Comment by NickolajA** [comment]
Could you share a printscreen of the Operating System Image object from the ConfigMgr console, showing the Image information?

**Comment by NickPifer86** [comment]
Interesting; SCCM is indeed showing the OS is 6.2.15063.296. I found [this article](https://social.technet.microsoft.com/Forums/en-US/6bb40939-c9ae-47a9-adee-b121ba77379a/windows-10-wrong-os-version-for-captured-image?forum=configmanagerosd) on the issue, so it looks like I'll need to recapture that image if I want to use it. 

That also explains why after I tried customizing the script to read "6.2*" as windows 10, the script was still unable to match any driver packages - it's using $OSImageVersion to do that. 

Thanks for the help, seems like the culprit was a bug in SCCM.
![2018-01-26_08h42_33](https://user-images.githubusercontent.com/35746787/35444717-05a88f5c-0275-11e8-84a8-cb127b81a596.png)

**Comment by NickPifer86** [comment]
Thanks again for your help; I recaptured a new image and now SCCM has the correct OS version in the properties of the OS Image. Now I'm facing a new issue, however. If you prefer for me to raise a separate issue for this let me know.

My ApplyDriverPackage.log now shows the OSImageVersion being retrieved correctly, but is failing to detect the OSImageArchitechture. My SMSTS.log shows exit code 4. Looking in SCCM, I can see the architechture property is "X64". 
![2018-01-29_10h38_27](https://user-images.githubusercontent.com/35746787/35521909-954c39ca-04e0-11e8-9043-9b2cb59005a1.png)
Just to be safe, I ran the powershell command shown below, and it looks like the actual value is "9". 
![2018-01-29_10h48_49](https://user-images.githubusercontent.com/35746787/35522527-3ced0cd0-04e2-11e8-97a6-03b79e8e933f.png)

I also decided to try troubleshooting by calling the webservice directly using Invoke-WebRequest, and below is the response I got:
![2018-01-29_10h58_23](https://user-images.githubusercontent.com/35746787/35523010-75c6bc08-04e3-11e8-8d71-10d3710fc994.png)

Here's the ApplyDriverPackage.log now:
[ApplyDriverPkg.log](https://github.com/SCConfigMgr/ConfigMgr/files/1674489/ApplyDriverPkg.log)

**Comment by NickolajA** [comment]
Are you PXE booting or using Boot Media? There's a known bug for Boot Media as the _SMSTSPackageID variable is not set with a proper value we rely on.

Also, your PowerShell code is a bit incorrect, try the following:

$WebService = New-WebServiceProxy -Uri $URI
$TSPackageID = "ENTER_PACKAGEID_HERE"
$WebService.GetCMOSImageArchitectureForTaskSequence($SecretKey, $TSPackageID)

It should hopefully return 9 (x64), which is the value set in the SMS Provider for the Image Information instance.

**Comment by NickPifer86** [comment]
We are PXE booting. 

When I run your PowerShell code, I do not get an error, but I also do not get a return value. It seems to successfully return nothing, even when I use other methods such as $WebService.GetCMOSImageVersionForTaskSequence for the same package, or try either method for other packages.

**Comment by chrisATautomatemystuff** [comment]
@NickolajA Do we need to use a CAPTURED image or can I simply use the imported WIM directly from the ISO? I haven't been in the practice of doing B&C in a while and don't want to start again if I don't have to. We're also running into the issue presented in this thread.

**Comment by grandslamjmh** [comment]
> @NickolajA Do we need to use a CAPTURED image or can I simply use the imported WIM directly from the ISO? I haven't been in the practice of doing B&C in a while and don't want to start again if I don't have to. We're also running into the issue presented in this thread.

I too would like to piggy back as I have the same question.
