### ISSUE TITLE
Dell 64BIT BIOS Flash Utility outdated

### ISSUE THREAD

**Issue by vartaxe** [SCConfigMgr/ConfigMgr#180]
there is a newer 2019 version bios flash tool out
https://www.dell.com/support/driver/us/en/04/DriversDetails?driverId=0R8CX
DAT keeps downloading and using the 2017 version

**Comment by vartaxe** [comment]
Fixes:
BIOS flash tool bypassed system ID check issue with /f /s
Fixed Utility closes accidently when check BitLocker status.
Fixes:
Fixed Flash64 not working with Windows 10 1809 Redstone 5

**Comment by jlf283** [comment]
Thank you for posting this. I have been pulling my hair out trying to figure out why this isn't working any longer. Any idea how to manually inject this into my packages since the tool doesn't seem to be pulling the new version yet?

**Comment by jlf283** [comment]
> Fixes:
> BIOS flash tool bypassed system ID check issue with /f /s
> Fixed Utility closes accidently when check BitLocker status.
> Fixes:
> Fixed Flash64 not working with Windows 10 1809 Redstone 5

I did notice they removed the not working piece from the site, though.

**Comment by NickolajA** [comment]
@maurice-daly - Have this been fixed in DAT?

**Comment by maurice-daly** [comment]
Issue has been fixed in the latest build.
