### ISSUE TITLE
log location

### ISSUE THREAD

**Issue by vartaxe** [SCConfigMgr/ConfigMgr#184]
for DeploymentType OSUpgrade, BIOSUpdate and DriverUpdate why not use $LogsDirectory = $Script:TSEnvironment.Value("_SMSTSLogPath") instead of $LogsDirectory = Join-Path -Path $env:SystemRoot -ChildPath "Temp" ?

**Comment by NickolajA** [comment]
Honestly I don't recall the reason for that change, but I'm sure it wouldn't be an issue.
