### ISSUE TITLE
Local Distribution Point Only

### ISSUE THREAD

**Issue by wsfrazier** [SCConfigMgr/ConfigMgr#185]
By chance found an issue of someone running our driver update task sequence while I was updating the driver packages in the console. The package wasn't distributed to our DPs yet, so when the person ran the task sequence, it pulled the package from our Primary SCCM server off-site in the DC.

Some of our sites have really bad connections, so pulling a driver package from an off-site server is a big no-no for us.

Is it possible to have the Invoke-CMApplyDriverPackage.ps1 determine if the driver package is located on that clients local DP defined by it's boundary group? If it's not found, then fail the task sequence?

If we can't do that, is there some type of condition I can set on the Dynamically Apply Drivers step in the task sequence to maybe check a content location variable? If it isn't set to the local DP, then skip the step?

Just looking for some options here.

Thanks

**Comment by NickolajA** [comment]
We've had similar discussions before, but came to the conclusion that it'd require too much work and lookups to successfully validate if it's available in the DP of the boundary group and decided it was not worth the effort, unfortunately. From the looks of it, it seems that you've had your Primary Site server added to the site default boundary group for fallback.
