### ISSUE TITLE
Driver Automation Tool 6.3.1 - Microsoft Surface Download

### ISSUE THREAD

**Issue by virtualtech516** [SCConfigMgr/ConfigMgr#190]
Hi,

I'm getting the following error when trying to download drivers and/or firmware for any of my Surface devices:

ConfigMgr: Extracting Microsoft Firmware to C:\Users\sccmadmin\Desktop\DriverAutomationTool\Temp\Surface Pro 5\Win10x64	DriverAutomationTool	10/5/2019 11:15:26 AM	5512 (0x1588)
ConfigMgr: Waiting for extract process (Process ID: 5332) to complete. Next check in 30 seconds	DriverAutomationTool	10/5/2019 11:15:26 AM	5512 (0x1588)
ConfigMgr: Waiting for extract process (Process ID: 5332) to complete. Next check in 30 seconds	DriverAutomationTool	10/5/2019 11:15:56 AM	5512 (0x1588)
ConfigMgr: Microsoft Firmware source directory set to C:\Users\sccmadmin\Desktop\DriverAutomationTool\Temp\Surface Pro 5\Win10x64	DriverAutomationTool	10/5/2019 11:16:26 AM	5512 (0x1588)
ConfigMgr: Package destination set to \\SERVER\SourceMedia\OSD\Drivers\Downloads\Microsoft\Surface Pro 5\Windows10-1903-x64-18362\Firmware	DriverAutomationTool	10/5/2019 11:16:26 AM	5512 (0x1588)
ConfigMgr: Moving Microsoft Surface Pro 5 Firmware. Next Check In 30 Seconds	DriverAutomationTool	10/5/2019 11:16:27 AM	5512 (0x1588)
ConfigMgr: Checking for extracted firmware	DriverAutomationTool	10/5/2019 11:16:57 AM	5512 (0x1588)
ConfigMgr: Import into is ConfigMgr - Standard Pkg	DriverAutomationTool	10/5/2019 11:16:57 AM	5512 (0x1588)
ConfigMgr: Firmware count in path \\SERVER\SourceMedia\OSD\Drivers\Downloads\Microsoft\Surface Pro 5\Windows10-1903-x64-18362\Firmware - 0 	DriverAutomationTool	10/5/2019 11:16:57 AM	5512 (0x1588)
======== DRIVER FIRMWARE ISSUE DETECTED ========	DriverAutomationTool	10/5/2019 11:16:57 AM	5512 (0x1588)
ConfigMgr: Issues occurred while reading extracted firmware	DriverAutomationTool	10/5/2019 11:16:57 AM	5512 (0x1588)
ConfigMgr: Firmware count in path  - 86 	DriverAutomationTool	10/5/2019 11:16:57 AM	5512 (0x1588)

**Comment by chaosisbliss** [comment]
I had to rename the surface pro 5 package nam l name in sccm to surface pro.
