### ISSUE TITLE
Errors with PS1 in TS

### ISSUE THREAD

**Issue by jonnwhite1** [SCConfigMgr/ConfigMgr#194]
Hey, 

Not sure if you can help with this however have the below error when running the PS1 through Ts. 
I followed the guide that was on the website on how to get it setup. 
Errors are:
[Drivers.txt](https://github.com/SCConfigMgr/ConfigMgr/files/3776068/Drivers.txt)

Also how the TS is calling it (Server is called sccm.joli.local not a type)

![ts](https://user-images.githubusercontent.com/51175698/67637357-ccd6e700-f8d1-11e9-8f1d-d1abddac646b.PNG)

Any help would be appreciated.

**Comment by NickolajA** [comment]
Seems that you're running it with Windows 7, that would require you to install WMF 5.0.
