### ISSUE TITLE
Dell BIOS that require incremental versions

### ISSUE THREAD

**Issue by prjoni99** [SCConfigMgr/ConfigMgr#196]
Hello,

I have been having some issues with the Dell 5289 BIOS management and I was wondering if there's a workaround to my issue. Dell 5289 BIOS updates are weird because you can't just upgrade to the latest version you have to do it incrementally based on the BIOS version currently installed in the system. Please let me know if there's a workaround if not we will do these models manually then.

Thanks!

**Comment by vartaxe** [comment]
i don't think there is a way to automate this...

**Comment by suprnova74** [comment]
Just thinking out of the box, you could  classify the prerequisite version as a different type in SCCM so it could be filtered and run the bios check twice.  so, for example, the 5289 needed 1.1 before updating to 2.0, you'd label 1.1 as BIOS PREREQ or similar, add that as the filter, then the main bios update could catch the 2.0.

**Comment by NickolajA** [comment]
@suprnova74 great suggestion.
