### ISSUE TITLE
DAT proxy support

### ISSUE THREAD

**Issue by vartaxe** [SCConfigMgr/ConfigMgr#198]
proxy settings in dat doesn't seem to be working... work around is to set it on internet explorer settings and leave dat settings blank

**Comment by maurice-daly** [comment]
I'm thinking of deprecating the proxy settings within the DAT. I've tested it with some proxies, but I am seeing less and less of them and for those that are there, they bring their own challenges if filtering is then taken into account. 

Thanks for the feedback though
