### ISSUE TITLE
Minor: Next check in 60 seconds sleep -seconds 30

### ISSUE THREAD

**Issue by stgrdk** [SCConfigMgr/ConfigMgr#2]
Hi, at line 10071-10072: 

10071: msg sleep for 60 seconds.
10072: sleep -seconds 30

Text and action should be equal.. This goes for all the other manufactures to.

**Comment by NickolajA** [comment]
Thank you for reporting this, I've assigned this issue to Maurice so that he can correct the sleep function.

**Comment by maurice-daly** [comment]
Fixed in 5.0.1
