### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 single driver install mode with spaces in path

### ISSUE THREAD

**Issue by tastrsks** [SCConfigMgr/ConfigMgr#201]
Hi,

There's an issue with Invoke-CMApplyDriverPackage.ps1 on line 889:
https://github.com/SCConfigMgr/ConfigMgr/blob/5005be8d0477d4b7d71a1084b0c4137710bc625e/Operating%20System%20Deployment/Drivers/Invoke-CMApplyDriverPackage.ps1#L889

The DISM command will fail if there's a space in the driver path. I changed it from `/Driver:$($DriverINF.FullName)"` to ``/Driver:`"$($DriverINF.FullName)`""`` which solved it in our environment.

**Comment by NickolajA** [comment]
Thank you for letting us know. Your fix has been committed to version 2.2.6.
