### ISSUE TITLE
Driver Automation Tool 6.4.1 - HP BIOS Extract Problem

### ISSUE THREAD

**Issue by Bra1984** [SCConfigMgr/ConfigMgr#204]
According to the log, following parameters are used to extract the package 

> Info: Using Hewlett-Packard silent switches: **-PDF -F**C:\Program Files\SCConfigMgr\Driver Automation Tool\Temp\HPBIOSTemp\ZBook Studio x360 G5 Convertible Workstation\Extract\ **-S -E**

The -PDF parameter dosen 't seem to work, I downloaded the BIOS exe file manually , please see the attachment 
![2020-01-10_1213](https://user-images.githubusercontent.com/29057819/72149192-e4871d00-33a2-11ea-92a1-7b77c9a1ba4b.png)

**Comment by Gor3t3x** [comment]
Having the same issue too
Exemple: HP EliteDesk 800 G5 Desktop Mini PC - Windows 10 1803.

I Extracted driver manually and it seems to contain driver for Windows 10 1809.

When i choose Windows 10 1809, extraction from Driver Automation Tool 6.4.1 is working fine.

Maybe a HP catalog problem?

Thanks

**Comment by MichaelGibsonAltrad** [comment]
I've had this on multiple models of HP. Also need to enclose the extract path passed to the softpaq in quotes as if you have spaces in your download path. Some require this, some don't so very hit and miss

**Comment by MichaelGibsonAltrad** [comment]
This problem also impacts the driver extract, not just the BIOS extract,

**Comment by NickolajA** [comment]
This should have been fixed in the latest version of DAT.
