### ISSUE TITLE
Driver Automation Tool - Process Review?

### ISSUE THREAD

**Issue by EvilerBetty** [SCConfigMgr/ConfigMgr#212]
I've opened a few issues that are still open, I'm going to try to recap and explain my process to make sure I'm not missing something.  Please reply if you have suggestions. ;)

I have a single site.  Single primary server with 175 DPs on slower circuits.

My process for updating drivers is:

1. Select Mfg / ConfigMgr-StdPkg / Win10 / Drivers / 64bit

2. Click "Start Download | Extract | Import".

**_*Now I have new driver packages in my target folder in SCCM.  To prevent OSD operations from trying to use these new packages before they are distributed to DPs, I need to move them to pilot.  I can't download them as Pilot packages, due to this issue:_**  [#169 - Driver Automation Tool 6.3.0 - Pilot Package / Mange to Prod](https://github.com/SCConfigMgr/ConfigMgr/issues/169)

3.  ConfigMgr Package Mgmt > PkgType: Driver > Deployment State: Production > Actions:  Move to Pilot.

4.  Distribute new driver packages to DPs.

5.  When complete, ConfigMgr Pakcage Mgmt > PkgType: Driver > Deployment State: Pilot > Actions:  Move to Production

6.  Move Driver Packages in SCCM to my final folder structure.

6.  Run "Start Download | Extract | Import" again to confirm there are no new driver packages available.

7.  Select "ConfigMgr Settings > select Remove Superseded Driver Packages", then "Start Download | Extract | Import" to cleanup old driver packages.

**_*If the previous step is enabled when running "Start Download | Extract | Import", even while the package is in Pilot, it will remove the current production driver._**

8. To prevent this for next time, select "ConfigMgr Settings > **unselect** Remove Superseded Driver Packages", then "Start Download | Extract | Import" to cleanup old driver packages.

**Comment by maurice-daly** [comment]
See the comment on 169. A fix is on its way!
