### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 and additional manufacturer (AZW)

### ISSUE THREAD

**Issue by Stuart42** [SCConfigMgr/ConfigMgr#213]
Hey,

I'm wondering how open you are to adding support for more (and more esoteric...) manufacturers.. we have an increasing number of super low-cost devices coming in from AZW, and I've found adding the following in the 'Determine manufacturer name and hardware information' section enables support for applying the custom driver packages we've made for them.

`		"*AZW*" {
			$ComputerManufacturer = "AZW"
			$ComputerModel = (Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model).Trim()
			$SystemSKU = (Get-CIMInstance -ClassName MS_SystemInformation -NameSpace root\WMI).BaseBoardProduct.Trim()
		}`

**Comment by NickolajA** [comment]
Absolutely, I'll add this to the new 3.0.0 version that's currently out in Preview. It'll be released soon.
