### ISSUE TITLE
New ZIP of driver Packages not working 

### ISSUE THREAD

**Issue by connorwilliams-aps** [SCConfigMgr/ConfigMgr#214]
The current version of the InvokeDriver script does not appear to be working with the new zipping function of the Modern to version 6.4.4. In my environment, the tool is building the zip files and packaging them properly, but when you attempt to use them in OSD, the zip file is not being unzipped after the move to the temp location. As a result, DISM doesnt see the ini files for the injection process and doesnt end up installing the drivers.

**Comment by merlinfrombelgium** [comment]
Currently, ZIP packages are supported only in the preview of version 3 of the script.

**Comment by NickolajA** [comment]
Merlin is correct, it's only in Preview at the moment, soon to be released.
