### ISSUE TITLE
I think there is a typo on line 202 of version 3.0.1 for string $Manufacturer

### ISSUE THREAD

**Issue by Mrgreen17** [SCConfigMgr/ConfigMgr#215]
![Annotation 2020-03-29 073821](https://user-images.githubusercontent.com/43708957/77851902-7deaf180-7190-11ea-9bef-2f8768fce6a8.png)

**Comment by NickolajA** [comment]
Thanks for reporting, fixed in 3.0.2

**Comment by Mrgreen17** [comment]
I still think line 202 has the typo on version 3.0.2
