### ISSUE TITLE
Unable to translate OS architecture using input object: 64 bits

### ISSUE THREAD

**Issue by m0rph0** [SCConfigMgr/ConfigMgr#218]
I've been using this great tool without issues, but recently we see several HP notebook failing.

HP Probook 650 G5
HP Elitebook 840 G6

<![LOG[[ApplyDriverPackage]: Apply Driver Package process initiated]LOG]!><time="11:22:21.543-120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Apply driver package deployment type: DriverUpdate]LOG]!><time="11:22:21.563120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Apply driver package operational mode: Production]LOG]!><time="11:22:21.564120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[[PrerequisiteChecker]: Starting environment prerequisite checker]LOG]!><time="11:22:21.570120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Supported computer platform detected, script execution allowed to continue]LOG]!><time="11:22:21.615120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Supported operating system version currently running detected, script execution allowed to continue]LOG]!><time="11:22:21.652120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Computer manufacturer determined as: Hewlett-Packard]LOG]!><time="11:22:21.976120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Computer model determined as: HP EliteBook 840 G6]LOG]!><time="11:22:21.979120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Computer SystemSKU determined as: 8549]LOG]!><time="11:22:21.983120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Computer model detection was successful]LOG]!><time="11:22:21.991120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Computer SystemSKU detection was successful]LOG]!><time="11:22:21.996120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Computer details successfully verified]LOG]!><time="11:22:21.999120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Determined primary computer detection method: SystemSKU]LOG]!><time="11:22:22.002120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[[PrerequisiteChecker]: Completed environment prerequisite checker]LOG]!><time="11:22:22.003120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[[WebService]: Starting ConfigMgr WebService phase]LOG]!><time="11:22:22.004120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Successfully connected to ConfigMgr WebService at URI: https://server/ConfigMgrWebService/Configmgr.asmx]LOG]!><time="11:22:22.698120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - Retrieved a total of '55' driver packages from web service matching operational mode: Production]LOG]!><time="11:22:23.262120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="1" thread="13208" file="">
<![LOG[ - **Unable to translate OS architecture using input object: 64 bits**]LOG]!><time="11:22:23.343120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="3" thread="13208" file="">
<![LOG[[ApplyDriverPackage]: Apply Driver Package process failed, please refer to previous error or warning messages]LOG]!><time="11:22:23.353120" date="03-31-2020" component="ApplyDriverPackage" context="XXX\YYY" type="3" thread="13208" file="">

Versions used / tested:

OS: Windows 10 1809 & 1909 x64
Webservice 1.8.0
Script version: 2.2.7 & 3.0.2

**Comment by NickolajA** [comment]
That's strange, I've never seen the value of '64 bits' coming from the GetCMOSImageForTaskSequence web service call. I'll add those in and commit it in 3.0.3. Could you please verify if it works once 3.0.3 is available?

**Comment by NickolajA** [comment]
It's available now.

**Comment by m0rph0** [comment]
Hi Nickolaj, v3.0.3 solved the problem. Thank you so much!

**Comment by NickolajA** [comment]
Great, thanks for letting me know!

**Comment by CalderX** [comment]
Hi! We are running the latest version 3.0.3 and we have  the same error: - Unable to translate OS architecture using input object: 64 bitar when running:

- Apply driver package deployment type: DriverUpdate

Greetings

Calle
