### ISSUE TITLE
Can't seem to figure this out

### ISSUE THREAD

**Issue by joshuaprice88** [SCConfigMgr/ConfigMgr#27]
We set up our TS and running script like in walkthrough. It doesn't seem to install the drivers as described. Do I need to modify the script to work properly or could I possibly be missing something causing this not to work?

**Comment by NBL-HEIM** [comment]
can you upload the ApplyDriverPackage.log and SMSTS.log file?

**Comment by joshuaprice88** [comment]
[smsts.log](https://github.com/SCConfigMgr/ConfigMgr/files/1731795/smsts.log)
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1731797/ApplyDriverPackage.log)
I changed my siteserver.fqdn in the smsts I uploaded but it is correct in the actual log.

**Comment by joshuaprice88** [comment]
Okay.....So I got it working by removing the Windows 7 install on the Test TS. We will still have to be able to use that because we have a district that is still using Windows 7 atm. We are now having issues where the HP devices are finding Duplicate packages like "HP Zbook 15 G3" and "HP Zbook 15 G3 Mobile Workstations" is there a way around this other than deleting the dups? I know according to SSM we have to have both for it to work.
