### ISSUE TITLE
Get-OSArchitecture in Invoke-CMApplyDriverPackage.ps1 does not translate non-english version of Windows 10

### ISSUE THREAD

**Issue by PZan** [SCConfigMgr/ConfigMgr#31]
When running the script with DeploymentType switched to "DriverUpdate" OS Arch is fetched from WMI. WMI will return the a translated string depending on the language of the OS.

For example in Norwegian:
`PS C:\> Get-WmiObject -Class Win32_OperatingSystem | Select-Object -ExpandProperty OSArchitecture`
returns:
`64-biters`
... and the function Get-OSArchitecture will not return a value.

An alternative solution would probably be to fetch the OS bitness from somewhere else than WMI when running DriverUpdate. Perhaps from $ENV:PROCESSOR_ARCHITECTURE or from [IntPtr]::Size

Possible solution:
```
function Get-OSArchitecture {
	param (
		[parameter(Mandatory = $true, HelpMessage = "OS architecture data to be translated.")]
		[ValidateNotNullOrEmpty()]
		[string]$InputObject
	)
	switch ($InputObject) {
		"9" {
			$OSImageArchitecture = "x64"
		}
		"0" {
			$OSImageArchitecture = "x86"
		}
		"64-bit" {
			$OSImageArchitecture = "x64"
		}
		"32-bit" {
			$OSImageArchitecture = "x86"
		}
		# Fetched from env:processor_architecture
		"AMD64" {
			$OSImageArchitecture = "x64"
		}
		# Fetched from env:processor_architecture
		"x86" {
			$OSImageArchitecture = "x86"
		}
	}
	Write-CMLogEntry -Value "Translated OSImageArchitecture: $($OSImageArchitecture)" -Severity 1
		
	# Handle return value from function
	return $OSImageArchitecture
}

$Arch = $ENV:PROCESSOR_ARCHITECTURE
Get-OSArchitecture -InputObject $Arch
```

**Comment by rtruss** [comment]
I too have seen this as a problem as I was using it for the language pack script (Invoke-CMDownloadLanguagePack) and ended up using this (which seems to have done the trick):


		switch -Wildcard ($InputObject) {
				"*9*" {
					$OSArchitecture = "x64"
				}
				"*0*" {
					$OSArchitecture = "x86"
				}
				"*64*" {
					$OSArchitecture = "x64"
				}
				"*32*" {
					$OSArchitecture = "x86"
				}						
			}
