### ISSUE TITLE
An error occurred while applying drivers (single package match). Exit code: 2. See DISM.log for more details.

### ISSUE THREAD

**Issue by gvanngo** [SCConfigMgr/ConfigMgr#32]
Tracking down the dism.log now.  Just wondering if you have seen this before.  The error in the ApplyDriverPackage.log file is An error occurred while applying drivers (single package match). Exit code: 2. See DISM.log for more details.  The SMSTS.log file states the following "Failed to run the action: Apply Drivers. Not enough storage is available to complete this operation. (Error: 0000000E; Source: Windows)" .  This would make sense however I've checked and the partitions are correct and there was over 200gb free space on the OSDrive.   

The majority of the failures were on Dell Optiplex 7050 and Optiplex 7010. Other models in our environment were fine. 

Thank you for your time.

**Comment by gvanngo** [comment]
DISM.log saved the day. Turns out it was the video driver failing to import.  I'm using an updated video driver NOT from the Dell .cab.  For me the 7050 A06 driver cab is the one with the bad Intel HD 630 driver.

**Comment by ekrizon** [comment]
This is happening for me on multiple different models as well.  I have just enabled the option "continue on error" on the step in the task sequence and it will still install the rest of the drivers fine.
