### ISSUE TITLE
Call to web service for package objects returned empty

### ISSUE THREAD

**Issue by joshuaprice88** [SCConfigMgr/ConfigMgr#33]
This is only happening on our HP machines, our Dell systems are working fine I don't understand what the difference is. Is there something I'm missing in the script that I need to change?

**Comment by ekrizon** [comment]
Hard to tell, you got logs?  Would you please post both SMSTS and ApplyDriverPackage logs from a failure

**Comment by Szymek68** [comment]
I am getting the same error #9 for MS Surface Pro 3 which might be a result of the following:
Computer model determined as: Surface Pro 3
Unable to determine system SKU value.
Is not MS hardware supported?

**Comment by EvilerBetty** [comment]
Same issue for Surface Pro 4 and Surface Pro 3.   All Dell models appear to be working.

Logs attached (and inserted below)

**Surface Pro 4** ApplyDriverPackage.log
`Driver download package process initiated		1/1/1601 12:00:00 AM	0 (0x0000)
Manufacturer determined as: Microsoft		1/1/1601 12:00:00 AM	0 (0x0000)
Computer model determined as: Surface Pro 4		1/1/1601 12:00:00 AM	0 (0x0000)
Unable to determine system SKU value		1/1/1601 12:00:00 AM	0 (0x0000)
Retrieved a total of 21 driver packages from web service		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to detect OSImageVersion property from task sequence, running in DeploymentType: BareMetal		1/1/1601 12:00:00 AM	0 (0x0000)
Retrieved OSImageVersion from web service: 10.0.16299.15		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to detect OSImageArchitecture property from task sequence, running in DeploymentType: BareMetal		1/1/1601 12:00:00 AM	0 (0x0000)
Retrieved OSImageArchitecture from web service: 9		1/1/1601 12:00:00 AM	0 (0x0000)
Translated OSName from OSImageVersion: Windows 10		1/1/1601 12:00:00 AM	0 (0x0000)
Translated OSImageArchitecture: x64		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Latitude E5450 - Windows 10 x64 (0010008E)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Latitude E5450 - Windows 10 x64 (0010008E)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Latitude E5470 - Windows 10 x64 (0010008F)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Latitude E5470 - Windows 10 x64 (0010008F)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell OptiPlex 3040 - Windows 10 x64 (00100090)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell OptiPlex 3040 - Windows 10 x64 (00100090)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 5040 - Windows 10 x64 (00100091)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 5040 - Windows 10 x64 (00100091)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 5050 - Windows 10 x64 (00100092)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 5050 - Windows 10 x64 (00100092)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7010 - Windows 10 x64 (00100093)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7010 - Windows 10 x64 (00100093)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7020 - Windows 10 x64 (00100094)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7020 - Windows 10 x64 (00100094)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7040 - Windows 10 x64 (00100095)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7040 - Windows 10 x64 (00100095)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7440 AIO - Windows 10 x64 (00100096)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7440 AIO - Windows 10 x64 (00100096)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 9030 AIO - Windows 10 x64 (00100097)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 9030 AIO - Windows 10 x64 (00100097)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision 5520 - Windows 10 x64 (00100098)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision 5520 - Windows 10 x64 (00100098)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision 7510 - Windows 10 x64 (00100099)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision 7510 - Windows 10 x64 (00100099)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision M4800 - Windows 10 x64 (0010009A)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision M4800 - Windows 10 x64 (0010009A)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision Tower 3620 - Windows 10 x64 (0010009B)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision Tower 3620 - Windows 10 x64 (0010009B)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision Tower 7810 - Windows 10 x64 (0010009C)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision Tower 7810 - Windows 10 x64 (0010009C)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface Pro - Windows 10 x64 (0010009D)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface Pro - Windows 10 x64 (0010009D)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface Pro 3 - Windows 10 x64 (0010009E)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface Pro 3 - Windows 10 x64 (0010009E)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface3 WiFi - Windows 10 x64 (001000A0)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface3 WiFi - Windows 10 x64 (001000A0)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - VMware VMware Virtual Platform - Windows 10 x64 (001000A4)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - VMware VMware Virtual Platform - Windows 10 x64 (001000A4)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Latitude 5480 - Windows 10 x64 (001000A6)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Latitude 5480 - Windows 10 x64 (001000A6)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface Pro 4 - Windows 10 x64 (001000A8)		1/1/1601 12:00:00 AM	0 (0x0000)
Match found for computer model using detection method: ComputerModel (Surface Pro 4)		1/1/1601 12:00:00 AM	0 (0x0000)
Call to web service for package objects returned empty		1/1/1601 12:00:00 AM	0 (0x0000)
`



**Dell E5470**  ApplyDriverPackage.log
`Driver download package process initiated		1/1/1601 12:00:00 AM	0 (0x0000)
Manufacturer determined as: Dell		1/1/1601 12:00:00 AM	0 (0x0000)
Computer model determined as: Latitude E5470		1/1/1601 12:00:00 AM	0 (0x0000)
Computer SKU determined as: 06DE		1/1/1601 12:00:00 AM	0 (0x0000)
Retrieved a total of 21 driver packages from web service		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to detect OSImageVersion property from task sequence, running in DeploymentType: BareMetal		1/1/1601 12:00:00 AM	0 (0x0000)
Retrieved OSImageVersion from web service: 10.0.16299.15		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to detect OSImageArchitecture property from task sequence, running in DeploymentType: BareMetal		1/1/1601 12:00:00 AM	0 (0x0000)
Retrieved OSImageArchitecture from web service: 9		1/1/1601 12:00:00 AM	0 (0x0000)
Translated OSName from OSImageVersion: Windows 10		1/1/1601 12:00:00 AM	0 (0x0000)
Translated OSImageArchitecture: x64		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Latitude E5450 - Windows 10 x64 (0010008E)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Latitude E5450 - Windows 10 x64 (0010008E)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Latitude E5470 - Windows 10 x64 (0010008F)		1/1/1601 12:00:00 AM	0 (0x0000)
Match found for computer model using detection method: SystemSKU (06DE)		1/1/1601 12:00:00 AM	0 (0x0000)
Match found for manufacturer, operating system and architecture: Drivers - Dell Latitude E5470 - Windows 10 x64 (0010008F)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell OptiPlex 3040 - Windows 10 x64 (00100090)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell OptiPlex 3040 - Windows 10 x64 (00100090)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 5040 - Windows 10 x64 (00100091)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 5040 - Windows 10 x64 (00100091)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 5050 - Windows 10 x64 (00100092)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 5050 - Windows 10 x64 (00100092)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7010 - Windows 10 x64 (00100093)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7010 - Windows 10 x64 (00100093)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7020 - Windows 10 x64 (00100094)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7020 - Windows 10 x64 (00100094)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7040 - Windows 10 x64 (00100095)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7040 - Windows 10 x64 (00100095)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 7440 AIO - Windows 10 x64 (00100096)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 7440 AIO - Windows 10 x64 (00100096)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Optiplex 9030 AIO - Windows 10 x64 (00100097)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Optiplex 9030 AIO - Windows 10 x64 (00100097)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision 5520 - Windows 10 x64 (00100098)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision 5520 - Windows 10 x64 (00100098)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision 7510 - Windows 10 x64 (00100099)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision 7510 - Windows 10 x64 (00100099)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision M4800 - Windows 10 x64 (0010009A)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision M4800 - Windows 10 x64 (0010009A)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision Tower 3620 - Windows 10 x64 (0010009B)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision Tower 3620 - Windows 10 x64 (0010009B)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Precision Tower 7810 - Windows 10 x64 (0010009C)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Precision Tower 7810 - Windows 10 x64 (0010009C)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface Pro - Windows 10 x64 (0010009D)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface Pro - Windows 10 x64 (0010009D)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface Pro 3 - Windows 10 x64 (0010009E)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface Pro 3 - Windows 10 x64 (0010009E)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface3 WiFi - Windows 10 x64 (001000A0)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface3 WiFi - Windows 10 x64 (001000A0)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - VMware VMware Virtual Platform - Windows 10 x64 (001000A4)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - VMware VMware Virtual Platform - Windows 10 x64 (001000A4)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Dell Latitude 5480 - Windows 10 x64 (001000A6)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Dell Latitude 5480 - Windows 10 x64 (001000A6)		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to find a match for driver package: Drivers - Microsoft Surface Pro 4 - Windows 10 x64 (001000A8)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package does not meet computer model criteria: Drivers - Microsoft Surface Pro 4 - Windows 10 x64 (001000A8)		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package list contains a single match, attempting to download driver package content		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDownloadPackages to: 0010008F		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDestinationLocationType to: Custom		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDestinationVariable to: OSDDriverPackage		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDestinationPath to: %_SMSTSMDataPath%\DriverPackage		1/1/1601 12:00:00 AM	0 (0x0000)
Starting package content download process, this might take some time		1/1/1601 12:00:00 AM	0 (0x0000)
Starting package content download process (WinPE), this might take some time		1/1/1601 12:00:00 AM	0 (0x0000)
Successfully downloaded package content with PackageID: 0010008F		1/1/1601 12:00:00 AM	0 (0x0000)
Attempting to download driver package 001000A8 content from Distribution Point		1/1/1601 12:00:00 AM	0 (0x0000)
Driver package content downloaded successfully, attempting to apply drivers using dism.exe located in: C:\_SMSTaskSequence\DriverPackage\0010008F		1/1/1601 12:00:00 AM	0 (0x0000)
Successfully applied drivers using dism.exe		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDownloadPackages to a blank value		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDestinationLocationType to a blank value		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDestinationVariable to a blank value		1/1/1601 12:00:00 AM	0 (0x0000)
Setting task sequence variable OSDDownloadDestinationPath to a blank value		1/1/1601 12:00:00 AM	0 (0x0000)
`


**SMSTS.log**
`Resolved source to 'C:\_SMSTaskSequence\Packages\001000AF'	RunPowerShellScript	3/21/2018 3:45:33 AM	1160 (0x0488)
Command line for extension .exe is "%1" %*	RunPowerShellScript	3/21/2018 3:45:33 AM	1160 (0x0488)
Set command line: Run Powershell script	RunPowerShellScript	3/21/2018 3:45:33 AM	1160 (0x0488)
Working dir 'C:\_SMSTaskSequence\Packages\001000AF'	RunPowerShellScript	3/21/2018 3:45:33 AM	1160 (0x0488)
Executing command line: Run Powershell script	RunPowerShellScript	3/21/2018 3:45:33 AM	1160 (0x0488)
Process completed with exit code 9	RunPowerShellScript	3/21/2018 3:46:00 AM	1160 (0x0488)
Command line returned 9	RunPowerShellScript	3/21/2018 3:46:00 AM	1160 (0x0488)
ReleaseSource() for C:\_SMSTaskSequence\Packages\001000AF.	RunPowerShellScript	3/21/2018 3:46:00 AM	1160 (0x0488)
reference count 1 for the source C:\_SMSTaskSequence\Packages\001000AF before releasing	RunPowerShellScript	3/21/2018 3:46:00 AM	1160 (0x0488)
Released the resolved source C:\_SMSTaskSequence\Packages\001000AF	RunPowerShellScript	3/21/2018 3:46:00 AM	1160 (0x0488)
Process completed with exit code 9	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
!--------------------------------------------------------------------------------------------!	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Failed to run the action: Dynamically Apply Drivers. 
The storage control block address is invalid. (Error: 00000009; Source: Windows)	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
MP server ConfigMgrSrv.Domain.com. Ports 80,443. CRL=false.	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Setting authenticator	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Set authenticator in transport	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Sending StatusMessage	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Setting message signatures.	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Setting the authenticator.	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
CLibSMSMessageWinHttpTransport::Send: URL: ConfigMgrSrv.Domain.com:80  CCM_POST /ccm_system/request	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Request was successful.	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Set a global environment variable _SMSTSLastActionRetCode=9	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Set a global environment variable _SMSTSLastActionSucceeded=false	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Clear local default environment	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Let the parent group (PostInstall) decides whether to continue execution	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
Let the parent group (Execute Task Sequence) decide whether to continue execution	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
The group (Execute Task Sequence) ignored action failure and continue execution on the next step following the group.	TSManager	3/21/2018 3:46:00 AM	1524 (0x05F4)
`
[SMSTS-SurfacePro4.log](https://github.com/SCConfigMgr/ConfigMgr/files/1834071/SMSTS-SurfacePro4.log)
[ApplyDriverPackage-SurfacePro4.log](https://github.com/SCConfigMgr/ConfigMgr/files/1834078/ApplyDriverPackage-SurfacePro4.log)
[ApplyDriverPackage-E5470.log](https://github.com/SCConfigMgr/ConfigMgr/files/1834079/ApplyDriverPackage-E5470.log)

**Comment by Szymek68** [comment]
Thanks for the script update. 
I ran it in the debug mode but still have the same issue for MS Surface Pro 3. 
Log file attached.
Call to web service for package objects returned empty	ApplyDriverPackage	22/03/2018 17:16:29	7796 (0x1E74)
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1838581/ApplyDriverPackage.log)

**Comment by ekrizon** [comment]
@Szymek68  and @EvilerBetty 

I mentioned this in Issue #28 https://github.com/SCConfigMgr/ConfigMgr/issues/28

At this time Surface models seem need the OS Image version in the Driver package name.

Rename your package in SCCM to this for example Surface Pro 4:

Drivers - Microsoft Surface Pro 4 - Windows 10 10.0.16299.15 x64

**Comment by EvilerBetty** [comment]
I tried this after seeing your recommendation on the other thread.  Also set the task to continue on error.  It  continued, but drivers were not installed.

I'm installing 1709.  My next step was to confirm that build version was 1709, and that the drivers pulled down by the automation tool were also the 1709 version (or whatever those codes on the different drivers represent).

**Comment by ekrizon** [comment]
Ya give it a go and post new logs if it still doesn't work.  The logs you posted above did not have the package renamed so that is why it didn't find a match correctly.

**Comment by Szymek68** [comment]
There is a better way of fixing it rather than changing the MS Surface package names. I update line 561 to be the same as default and all works fine.: if ($Package.PackageName -match $OSName) {. 
Now this is fully aligned with the Driver Automation Tool  and works perfectly fine.

**Comment by ekrizon** [comment]
@Szymek68 Great work!  You should submit that to the SCConfigMgr guys so it gets fixed.

**Comment by Szymek68** [comment]
@NickolajA We spotter a minor mistake in line 561 as Microsoft driver packages have a different name now.
The line should be as for default: if ($Package.PackageName -match $OSName) - tested works fine.

**Comment by Szymek68** [comment]
Yes, no change to the package name but instead replacing 
if ($Package.PackageName -match $OSImageVersion)      (line 561)
with
if ($Package.PackageName -match $OSName)

**Comment by EvilerBetty** [comment]
Ah, that's line 5**16** in script version 2.0.6.

Testing it now.

**Comment by Desite75** [comment]
Line 554 in script version 2.0.8.

**Comment by ruiqiu** [comment]
I have same result. from the ApplyDriverpackage.log, it sucessfuly recgonized my computer as HP 820 G2 Notebook PC, however it returned the same error in the end:
Match found for computer modedl using detection method: SystemSKU (225A)
Call to web service for package objects returned empty.
