### ISSUE TITLE
I don't believe Winuptp can take a password

### ISSUE THREAD

**Issue by MelQL** [SCConfigMgr/ConfigMgr#36]
If a password is passed into Invoke-LenovoBIOSUpdate.ps1, it builds the command line as Winuptp /S /pass:<password>.  From all I can find, Winuptp does not take a supervisor password and I believe that parameter will just be ignored.  To test, I tried just calling Winuptp /S /pass:<password> outside of this script and I am prompted for a password in that case.  The only thing I've found on whether Winuptp takes a password is this thread that indicates it does not:  https://forums.lenovo.com/t5/Enterprise-Client-Management/Winuptp-BIOS-flashing-with-existing-supervisor-password-PAP/td-p/3937076.

With Lenovo systems, you do not need a password to update the BIOS if "Flash BIOS updating by End-Users" is set to Enabled.  So for many, it won't be a problem if Winuptp does not take a password and the script will work fine (the password is ignored, but you don't need it anyway if "Flash BIOS updating by End-Users" is enabled).  Unfortunately, our thousands of systems that we need to update have "Flash BIOS updating by End-Users" disabled because we don't want our end-users to update the BIOS themselves.

I'm hoping I'm missing something about Lenovo systems and being able to pass a password into Invoke-LenovoBIOSUpdate.ps1 when using on a system that has a supervisor password and "Flash BIOS updating by End-Users" is disabled.

**Comment by fredfanatics** [comment]
We have the same problem. We use wmi to change the BIOSUpdateByUser-value.
[Lenovo BIOS Setup via WMI](https://support.lenovo.com/de/de/solutions/ht100612)
