### ISSUE TITLE
Driver packages are not being retrieved

### ISSUE THREAD

**Issue by allencQ85** [SCConfigMgr/ConfigMgr#360]
I am trying to integrate this DAT tool, but whenever i try to Get all Driver packages,  using the TestModernDrivermanagement.ps1,  i get NO output.  its as if there is no drivers at all.
 But when i run Get all Packages line,  it see get everything else except the Driver packages.

 Yes, my service account has read-only analyst permission.
 Wierd part is when i download my driver package (dell 5420) or Lenovo L14,  I dont see the system SKU being added in the package properties details.!!  Not sure if it related or not.  

what can i do to get the driver packages to be detected by the by the AdminService.
Anyone to assist please ?
Thanks

**Comment by allencQ85** [comment]
More info on error :
 Retrieved a total of '0' driver packages from AdminService matching operational mode: Production	ApplyDriverPackage	2023-12-06 2:19:19 PM	5660 (0x161C)

when i use the browser,  i dont see any output either..
https://FQDN/AdminService/wmi/SMS_Package?$filter=contains(Name,%27Drivers%27)

**Comment by allencQ85** [comment]
i figured my issue out,.
1.  i was not using ConfigMgr- Standard pkg selection,  instead i used ConfigMgr- Driver pkg, which created the regular packages with lots of inf files.. 
2.  i was getting issues with TLS/SSL mismatch,  and found out i had an expired personal certficate. after reading this link.
   https://www.reddit.com/r/SCCM/comments/znxft9/sms_rest_provider_warning_status_could_not/

**Comment by allencQ85** [comment]
i hope this helps someone else trying to use this tool out there

**Comment by merlinfrombelgium** [comment]
Thank you for sharing what you found! Glad you got it sorted quickly :)
