### ISSUE TITLE
Drivers not being applied to system.

### ISSUE THREAD

**Issue by joshuaprice88** [SCConfigMgr/ConfigMgr#37]
Dell M4700 getting this error, not sure what's causing it. Looks like it's passing Dism but then it hits the second pass since all were not working on PnP and uninstalls them. We have several different models between HP and Dell and this is only one doing this.

Unable to establish a connection to ConfigMgr WebService. Error message at line 417: There was an error downloading 'http://siteserver.domain.com/ConfigMgrWebService/ConfigMgr.asmx'.

**Comment by RajCM01** [comment]
Hi joshuaprice88, 

Were you able to resolve this, I am also having similar issue.

Thanks
Raj

**Comment by joshuaprice88** [comment]
I think we were. But we don’t image the M4700 anymore I’m not sure what the fix ended up being. Sorry :(

**Comment by RajCM01** [comment]
No problem, We are getting the same error on a different model, anyways will research more on this.
Thanks
