### ISSUE TITLE
Invoke-CMApplyDriverPackage Does Not Support Windows 7

### ISSUE THREAD

**Issue by Dmckee2018** [SCConfigMgr/ConfigMgr#38]
Hi Team,
As mentioned in the Driver Automation Tool forum, the current implementation of using PNPUtil to install on Windows 7 based computers fails miserably. To see why simply run the PNPUtil command used in Invoke-CMApplyDriverPackage as these functions are not supported until Windows 8. 
pnputil /add-driver /subdirs /install are all unsupported command line options for PNPUtil for Windows 7. The version in Windows 7 only supports -a, -i, -e etc, and does not support /add-driver /subdirs /install so it does nothing but error out. I can only assume your support for Windows 7 was never tested? 
 
Now I had thought about adding a Windows 7 based command to get around this but again run into problems with subdirectores which are again unsupported with this version of PNPUtil. So now I am thinking about using DPINST for the command and adding it to all Driver Packages, but I would prefer to continue to use your script as is. Would love it if you guys added this for Windows 7 computer or an option to use with PNPUtil like you do with DISM as that would fix the problem on Windows 7. 

MS state the Legacy switches are still usable but say nothing about Windows 7 not supporting the later commands. 
![image](https://user-images.githubusercontent.com/37912547/38108396-b0f23d04-3362-11e8-8b05-a97bbf7076db.png)

Thanks
David

**Comment by EvilerBetty** [comment]
Same issue, do we need to code a solution into the script our self, or is there a work-around?
