### ISSUE TITLE
Package content download process failed with return code -2147024809

### ISSUE THREAD

**Issue by Tsonga87** [SCConfigMgr/ConfigMgr#41]
Hi there,

First off - love this tool! Genuinely looks like it could change the way we handle drivers and BIOS! Thank you so much for your work on this.

That being said, we are having issues implementing it, currently resulting in '_Package content download process failed with return code -2147024809_' appearing in the ApplyDriverPackages.log.

The SMTS logs are showing '_Failed to move package PRD00166 from '' to 'C:\_SMSTaskSequence\DriverPackage\PRD00166' (0x80070057)'.

The task sequence is set to access content from the DP rather than download it locally, and this is our preference.

Any help is greatly appreciated (I have also posted this on reddit to seek help).

**Comment by Mrgreen17** [comment]
I am having the same issue with Lenovo package, it works with 1803 driver package  but not 1809 
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/3010011/ApplyDriverPackage.log)

**Comment by bnewhard** [comment]
Having same problem using the bios updating from software center.  ApplyBiosPackage.log shows new bios version available but errors grabbing the content.  all works fine during actual imaging TS in BareMetal mode.  Deployment is set to "download content" as this must work over Wifi, and variety of VPN solutions.  DP's are using http as well as the webserivce.  attached should be the relavent section of both the applybiospackage.log from Windows\temp and the smsts.log
[SMSTS log snippet.txt](https://github.com/SCConfigMgr/ConfigMgr/files/4215100/SMSTS.log.snippet.txt)

[ApplyBIOSPackage.log snippet.txt](https://github.com/SCConfigMgr/ConfigMgr/files/4215064/ApplyBIOSPackage.log.snippet.txt)
