### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 in Sub Task Sequence

### ISSUE THREAD

**Issue by manu4219** [SCConfigMgr/ConfigMgr#44]
Hello,

Firstly, many thanks!
If I run Invoke-CMApplyDriverPackage.ps1  from a simple TS, it's work fine.
I have a main TS.  From this TS, I run a other TS where I call Invoke-CMApplyDriverPackage.ps1.
In this case, it's not working, the ApplyDriverPackage.log is almost empty (please see joined file).
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1951414/ApplyDriverPackage.log)

Could advice?

Thanks in advance.

Regards,

**Comment by Fathi0** [comment]
Same problem here. The script doesn't work from a child task sequence if the apply OS step is not in the main TS. It uses the packageID of the main TS and finds nothing so drivers don't get applied. It should be possible to fix this by having a TS variable to specify what packageID GetCMOSImageForTaskSequence should use to retrieve OSImages.
