### ISSUE TITLE
BIOS updates are failing for Lenovo P320 Tiny

### ISSUE THREAD

**Issue by skywayskase** [SCConfigMgr/ConfigMgr#50]
I've been using these scripts for several months now and am very happy with them. We mostly run Lenovo laptops on the Windows side, but recently started purchasing a few Thinkstation P320 Tiny's. We noticed that when trying to image the Thinkstations, the task sequence fails when running the Invoke-LenovoBIOSUpdate script. This is working fine on all of our Thinkpads, and I made sure we have the most recent commit. I also made sure the BIOS package is the most recent, and that it's for the correct model. I'm attaching a screenshot as well as some logs from our most recent attempt.
![bios update error for p320 tiny](https://user-images.githubusercontent.com/11436704/40801450-cf507018-64c7-11e8-9fb1-5c9ad5f02738.jpg)
[smsts.log](https://github.com/SCConfigMgr/ConfigMgr/files/2059603/smsts.log)
[Invoke-LenovoBIOSUpdate.log](https://github.com/SCConfigMgr/ConfigMgr/files/2059604/Invoke-LenovoBIOSUpdate.log)
[LenovoFlashBiosUpdate.log](https://github.com/SCConfigMgr/ConfigMgr/files/2059605/LenovoFlashBiosUpdate.log)
[ApplyBIOSPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2059606/ApplyBIOSPackage.log)

**Comment by dpknoll** [comment]
We're seeing this too on M900 and M910q Tiny's. It appears that Lenovo is using the Flash.cmd - for 32 bit systems and Flash64.cmd - for 64 bit systems. The batch file calls the correct wflash2.exe or wflash2x64.exe file with some other parameters. I haven't experimented with modifying the Invoke-LenovoBIOSUpdate.ps1 file but know that changes will need for this to work on the Tiny's and perhaps other Lenovo desktops.

**Comment by rtruss** [comment]
We too are seeing this and on P500 units.  I had looked at the code to add support for the Lenovo miix tablets and thought something was missing for 64 v 32  I worked on it a bit and am almost ready to test it out.

Her eis what I am going to test:
	# Flash CMD upgrade utility file name
	if (([Environment]::Is64BitOperatingSystem) -eq $true) {
		$FlashCMDUtility = Get-ChildItem -Path $Path -Filter "*.cmd" -Recurse | Where-Object { $_.Name -like "Flash64.cmd" } | Select-Object -ExpandProperty FullName
        if (!$FlashCMDUtility){$FlashCMDUtility = Get-ChildItem -Path $Path -Filter "*.cmd" -Recurse | Where-Object { $_.Name -like "Flash.cmd" } | Select-Object -ExpandProperty FullName}
	}
	else {
		$FlashCMDUtility = Get-ChildItem -Path $Path -Filter "*.cmd" -Recurse | Where-Object { $_.Name -like "Flash.cmd" } | Select-Object -ExpandProperty FullName
	}

**Comment by rtruss** [comment]
Sadly I have not been able to get a test done yet, the techs manually updated the bios and now I have to wait for another unit to need a bios update.

**Comment by CTurnerSTL** [comment]
Anyone figure out a fix for this one?  I see this issue as well.  
Hoping to get some more testing in tomorrow.  May end up just disabling the BIOS updates for ThinkCentre's until I figure out another option.

**Comment by rtruss** [comment]
Hi all.  I am pretty sure I have it working for our environment now, that is to say I no longer see that message whether it actually updates I did forget to check but my techs are not complaining anymore.  I hope I attached the right script as I have one in my dev and one in my test and of course they do not match at the moment but they have the same amount of lines in them.  UGH.  I attached my "Dev" script for you all to take a look.

We also have a WIDE array of Lenovos, old M91, and new, Miix 520, so I had to address those as well as the x64 based update files.

[Invoke-LenovoBIOSUpdate.zip](https://github.com/SCConfigMgr/ConfigMgr/files/2680304/Invoke-LenovoBIOSUpdate.zip)

**Comment by OftKilted** [comment]
>           Sadly I have not been able to get a test done yet, the techs manually updated the bios and now I have to wait for another unit to need a bios update.

Typically you can do a rollback on BIOS updates for the Lenovo devices. (unless you have that hard-configured in the BIOS to not allow rollback, or the BIOS is a 'breakpoint' BIOS that enforces a non-rollback) typically you take the OLD bios dat file, drop it into the folder with the new updater and then re-run the 'updater' to roll it back to the prior version.

**Comment by CTurnerSTL** [comment]
I tried out the script.  It does not seem to do any updates on the devices I tested.  M600, M900, M910.  Most of my ThinkPad BIOS's are up to date but I did find a Yoga 260 that was pre-2018 BIOS and it did not get updated.  The error messages on the desktops no longer appear but they did not update.  Could possibly be why the tech's don't report issues.  I am hopefully going to get some time to dig into it more soon.  

Slammed right now documenting instructions for tech's so they can move devices from Win7 Pro to Win10 Ent.

**Comment by OftKilted** [comment]
M900 and m910 require s different process from the laptops as they have a different bios vendor and need to have a complete shutdown to handle the bios update. They can’t use a task sequence shutdown... it has to be a SMSTSPostAction with a shutdown /c (as I recall)

**Comment by CTurnerSTL** [comment]
I was doing some research on adjusting various settings in the Lenovo BIOS to automate some configuration settings and I came across this about ThinkCentre BIOS updates on the following Lenovo page...
https://download.lenovo.com/cdrt/wp/bios.html
### In WinPE, ThinkCentre has one limitation. ThinkCentre does not have a 64-bit installer. This results in ThinkCentre only being able to have its BIOS updated in an x86 version of WinPE.

Don't really use x86 these days.
