### ISSUE TITLE
Invoke-HPBIOSUpdate.ps1 not working on HP Elitebook 850 G5

### ISSUE THREAD

**Issue by peardvl** [SCConfigMgr/ConfigMgr#54]
Hi, 

The BIOS download powershell script works for HP Elitebook 850 G5, but the HP bios flash powershell script gives this error:

<![LOG[Work directory set as C:\_SMSTaskSequence\BIOSPackage\P0100BF4]LOG]!><time="15:01:44.653+60" date="06-08-2018" component="HPBIOSUpdate.log" context="NT-MYNDIGHET\SYSTEM" type="1" thread="12168" file="">
<![LOG[Initiating script to determine flashing capabilities for HP BIOS updates]LOG]!><time="15:01:44.727+60" date="06-08-2018" component="HPBIOSUpdate.log" context="NT-MYNDIGHET\SYSTEM" type="1" thread="12168" file="">
<![LOG[Supported upgrade utility was not found.]LOG]!><time="15:01:44.783+60" date="06-08-2018" component="HPBIOSUpdate.log" context="NT-MYNDIGHET\SYSTEM" type="3" thread="12168" file="">
<![LOG[Work directory set as C:\_SMSTaskSequence\BIOSPackage\P0100BF4]LOG]!><time="15:10:59.507+60" date="06-08-2018" component="HPBIOSUpdate.log" context="NT-MYNDIGHET\SYSTEM" type="1" thread="92" file="">
<![LOG[Initiating script to determine flashing capabilities for HP BIOS updates]LOG]!><time="15:10:59.584+60" date="06-08-2018" component="HPBIOSUpdate.log" context="NT-MYNDIGHET\SYSTEM" type="1" thread="92" file="">
<![LOG[Supported upgrade utility was not found.]LOG]!><time="15:10:59.642+60" date="06-08-2018" component="HPBIOSUpdate.log" context="NT-MYNDIGHET\SYSTEM" type="3" thread="92" file="">

here are the files that are downloaded:
![image](https://user-images.githubusercontent.com/40069025/41170520-e3eb2140-6b4c-11e8-9b07-751e81a2258b.png)

Windows 10 version 1803.

Thanks :)

**Comment by psxc2k3** [comment]
You can fix this by changing line 104-110 in Invoke-HPBIOSUpdate.ps1 to the following (I've only changed line 106 and 109, but for context I paste all lines):
	# HPBIOSUpdate bios upgrade utility file name
	if (([Environment]::Is64BitOperatingSystem) -eq $true) {
		$HPBIOSUPDUtil = Get-ChildItem -Path $Path -Filter "*.exe" -Recurse | Where-Object { $_.Name -imatch "HPBIOSUPDREC64.exe|HpFirmwareUpdRec64.exe" } | Select-Object -First 1 -ExpandProperty FullName	
	}
	else {
		$HPBIOSUPDUtil = Get-ChildItem -Path $Path -Filter "*.exe" -Recurse | Where-Object { $_.Name -like "HPBIOSUPDREC.exe|HpFirmwareUpdRec.exe" } | Select-Object -First	1 -ExpandProperty FullName	
	}

**Comment by Gor3t3x** [comment]
@peardvl resolved in last version, got it working without problems on HP 840 & 850 G5.
