### ISSUE TITLE
Support for older drivers for some HP models

### ISSUE THREAD

**Issue by PanuSaukko** [SCConfigMgr/ConfigMgr#55]
Any plans to add to a support that some HP models could use drivers from older Windows 10 build? HP doesn't provide Win10 1803 drivers for e.g. 820 G4, but Win10 1709 drivers are compatible with Win 10 1803.

**Comment by SPatrickStevens** [comment]
I created this pull request https://github.com/SCConfigMgr/ConfigMgr/pull/52 to address the HP issue. It would certainly be helpful for me if this was implemented. I'm sure what I created can be expanded upon, but it gets the job done.
