### ISSUE TITLE
HP EliteBook 840 G5 and HP ZBook 15u G5 has the same SystemSKU

### ISSUE THREAD

**Issue by psxc2k3** [SCConfigMgr/ConfigMgr#57]
Not sure how to best fix this one. It looks like there are two models With the same SystemSKU. A possible solution would be to match the name of the driver package to the model where this is the case. In a future Version perhaps?

**Comment by Gor3t3x** [comment]
it is the case in the latest version, it matches the SKU, and then the name of the package, and if there is a match on the package name, it drops the SKU one.

I had the problem previously with HP840G5 and HP850G5 matching the same SKU, and with both packages, an error was telling too many packages available somth like that.

Now, no more problems having different packages with same sku ^^

**Comment by psxc2k3** [comment]
I've fixed this with a codechange I've added in issue #65 - This issue is therefore a duplicate and can be deleted.
