### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 script error

### ISSUE THREAD

**Issue by CarlosAdam** [SCConfigMgr/ConfigMgr#58]
I have followed the instructions for the modern driver management.  I am getting the following error trying to run the script from within the task sequence.  I have also tried running it outside of the task sequence and get the same error.  Any suggestions?

D:\Sources\Scripts\ApplyDriverPackage\Invoke-CMApplyDriverPackage.ps1 : Cannot validate argument on parameter
'InputObject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command
again.
At line:1 char:1
+ .\Invoke-CMApplyDriverPackage.ps1 -URI "http://configmgrserver.test.com/ConfigMgrWebService/ConfigMgr.asmx" -SecretKey "4d34621b-cg79-30de-7545-8cbde4f47fc0" -Filter "Drivers" 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-CMApplyDriverPackage.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-CMApplyDriverPackage.ps1

**Comment by ThomasFaherty** [comment]
I am seeing the same thing with mine. 

"+ FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-CMApplyDriverPackage.ps1"

Makes me think there is something wrong with the FQDN but I don't know what. You ever solve this?
