### ISSUE TITLE
Add Trim to each of these

### ISSUE THREAD

**Issue by zakgodwin** [SCConfigMgr/ConfigMgr#60]
The following line and maybe the other makes being checked should trim the returned response. https://github.com/SCConfigMgr/ConfigMgr/blob/71ed7f14cb10fed81a1db26e82c7e5b5f6a23863/Operating%20System%20Deployment/Drivers/Invoke-CMApplyDriverPackage.ps1#L481

Example: `($ComputerModel = Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty Model).Trim() `

We've found devices with trailing white space in the model name then the script fails to match the model and drivers are not applied.

**Comment by vorlon77** [comment]
Yes, something like this is generally needed for Dell computers.

**Comment by NickolajA** [comment]
This will be added in 2.1.6
