### ISSUE TITLE
OS is pulling from web service as different from what was laid down.

### ISSUE THREAD

**Issue by joshuaprice88** [SCConfigMgr/ConfigMgr#62]
During the TS, when the script runs it's pulling my machine as Windows 7. It's getting imaged as Windows 10, not sure why it would be doing this. Any Help would be appreciated

**Comment by joshuaprice88** [comment]
Here are the logs from one of our machines.
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2215344/ApplyDriverPackage.log)
[BIOSPackageDownload.log](https://github.com/SCConfigMgr/ConfigMgr/files/2215345/BIOSPackageDownload.log)

**Comment by NickolajA** [comment]
Do you have multiple Apply Operating System steps in your task sequence?

**Comment by joshuaprice88** [comment]
I do and I'm creating the task sequence variable to direct it to the Windows 10 OS. But when I do the 
-OSImageTSVariableName parameter is not recognized as a parameterand the Script fails to run.
