### ISSUE TITLE
Issue with Task deployment setting Access Content directly from a distribution point when needed by the running task sequence

### ISSUE THREAD

**Issue by rtruss** [SCConfigMgr/ConfigMgr#63]
[Languagepackdownload-info.txt](https://github.com/SCConfigMgr/ConfigMgr/files/2229116/Languagepackdownload-info.txt)

As the title mentions when using that option tasks fail (language pack download for this instance) with this error:
Package content download process failed with return code -2147467259.

I have attached a txt file with some log file excerpts to help figure this out.  We are configured for https and data is configured using the option to use it from the server itself.

Now that the data has replicated after using powershell to make sure the setting CopyToPackageShareOnDistributionPoint was set on my language packs I got this error: Language pack package content download process returned an unhandled exit code: -2147024809.

Any help will be greatly appreciated

**Comment by NickolajA** [comment]
Yeah that's not a supported scenario unfortunately. We're using the built-in mechanism of ConfigMgr and that's where it doesn't work, as the executable can't handle such configurations.

**Comment by jlf283** [comment]
@NickolajA Am I understanding correctly that if we are then streaming our .WIM file from the DP to apply OS, that the Invoke-CMApplyDriverPackage.ps1 script will fail by design?
