### ISSUE TITLE
Issue with Invoke-CMDownloadBIOSPAckage.ps1

### ISSUE THREAD

**Issue by JvanderLin** [SCConfigMgr/ConfigMgr#64]
On the HP Probook 440 and 450 G5 the BIOS-version is in the form of 01.02.05. $CurrentBIOSVersion is constructed from SystemBiosMajorVersion and SystemBiosMinorVersion, which resolves to 2.5 in this particular case (line 335 in version 2.0.6 of the script). As a result the comparison fails to detect an update is available.

From ApplyBIOSPackage.log:
Current BIOS release detected as 2.5.
Available BIOS release deteced as 01.02.07.
BIOS is already up to date with the latest 01.02.07 version (!)

**Comment by Gor3t3x** [comment]
Same problem here with HP 840G5 and 850G5. The new bios are 01.01.08.

Changed version of the Bios Package to 01.08 to bypass this detection problem.

Strangely, HP 800G3 Bios are like 02.17 ... So it is working as Expected... HP is not helping with this lack of "standardization"

**Comment by enRchi** [comment]
I'm also having troubles with the Version matching. For me it's with the EliteDesk 800 G2.

At first it says:
_"<![LOG[Current BIOS version determined as: N01 Ver. 02.16"_
Then it finds an Update:
_<![LOG[Match found for computer model using detection method: SystemSKU (8054)
<![LOG[Match found for computer model and manufacturer: BIOS Update - Hewlett-Packard EliteDesk 800 G2 Small Form Factor PC (WZ1001F2)_

But after that it says:
_<![LOG[Current BIOS release detected as ..]LOG]!>
<![LOG[Available BIOS release deteced as 02.30.]LOG]_

Looks like it lost the Current BIOS value.

And if i look into the smsts.log i get the following error:
_"Compare-BIOSVersion : Der Wert "." kann nicht in den Typ "System.Version" konvertiert werden. Fehler: "Die Eingabezeichenfolge hat das falsche Format.""_

Rough Translation: The value "." can not be converted into the type "System.Version". Error: The input character string has the wrong format"

**Comment by enRchi** [comment]
Looks to me like the version is always XX.XX, so i replaced the following code:

_$CurrentBIOSVersion = "$($CurrentBIOSProperties.SystemBiosMajorVersion).$($CurrentBIOSProperties.SystemBiosMinorVersion)"_
With this:			
_$CurrentBIOSVersion = $CurrentBIOSProperties.SMBIOSBIOSVersion
$CurrentBIOSVersion = $CurrentBIOSVersion.Substring($CurrentBIOSVersion.Length - 5)_

Basically i'm using "N01 Ver. 02.16" and cut it down to the last 5 characters (02.16)

Will have to wait and see if this works with all our models. But looks good so far.

_<![LOG[Current BIOS release detected as 02.16.]LOG]
<![LOG[Available BIOS release deteced as 02.30.]LOG]_

**Comment by JvanderLin** [comment]
If that turns out to globally work it would be way more elegant than the SystemSKU based exceptions I've defined.

**Comment by enRchi** [comment]
I made an optimized version of this now. Basically i'm just taking the last "word" from the string. That way it doesn't matter if the Version is XX.XX.XX or XX.XX or X.XX or whatever ;) 


Original Code:
`$CurrentBIOSVersion = "$($CurrentBIOSProperties.SystemBiosMajorVersion).$($CurrentBIOSProperties.SystemBiosMinorVersion)"`

My changed Code:
`$CurrentBIOSVersion = $CurrentBIOSProperties.SMBIOSBIOSVersion | %{$_.Split() | Select -Last 1}`


Hope this works for you too. I don't have a ProBook 440 to check the SMBIOSBIOSVersion value.

**Comment by JvanderLin** [comment]
Confirmed working for HP Probook 440 G5.

**Comment by Gor3t3x** [comment]
For those who changed package to "xx.xx" to bypass this problem on some computers, careful using enRchi version posted, it will result in mandatory bios update each time.

You need to change back the version of the package to xx.xx.xx instead of xx.xx if the version detected is xx.xx.

For exemple:
computer has version 01.01.08 installed, it will detect current bios as 01.01.08 and available 01.08 and consider 01.08 is newer than 01.01.08 => will cause to reinstall same driver package every time.

So, not a problem with enRchi solution but could be a problem for whom changed package versions before.

Cya :)
