### ISSUE TITLE
Doesnt work for non Flash64w.exe

### ISSUE THREAD

**Issue by leebow55** [SCConfigMgr/ConfigMgr#69]
Hello there, making use of your great Modern Driver and BIOS Management utilities quite extensively.
I have a Dell 9010 that has the following BIOS flash utility - O9010A30.exe and no other files.

Will try and have a look at script myself tomorrow
![image](https://user-images.githubusercontent.com/17290500/45056266-48505600-b08a-11e8-90a0-e5ee91ee3c67.png)

**Comment by NickolajA** [comment]
Hi, we don't have access to such hardware unfortunately. If you could share the full command to work for that file, we could add the required modifications to the script.
