### ISSUE TITLE
Surface Pro 1796 failing computer model detection

### ISSUE THREAD

**Issue by wisniphi** [SCConfigMgr/ConfigMgr#74]
It would seem the Surface Pros now have the 1796 appended at the end of the model name and it is now failing to detect via computermodel.

The underscores are being correctly removed by if I understand the script correctly the 1796 not being included in the package name and seems to be included in the model name may be causing detection to fail.

[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2447812/ApplyDriverPackage.log)

Edit: Confirmed the install functions properly after appending " 1796" to the end of "Surface Pro" on the Package.

**Comment by quazl** [comment]
Could you elaborate what the before and after name of the package?

Thanks,

**Comment by quazl** [comment]
>           Could you elaborate what the before and after name of the package?
> Thanks,

I figured it out.

**Comment by wisniphi** [comment]
Also now happening with SP6. Log attached.
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2601508/ApplyDriverPackage.log)
