### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 v 2.1.5 small problem

### ISSUE THREAD

**Issue by JoelFrance** [SCConfigMgr/ConfigMgr#76]
Hi - found another glitch:
shouldn't  line 888 be:
$PackageNameComputerModel = $PackageList[$i].**Replace($ComputerManufacturer, "")**.Replace(" - ", ":").Split(":").Trim()[1]
instead of:
$PackageNameComputerModel = $PackageList[$i].**PackageName.Replace("Hewlett-Packard", "HP")**.Replace(" - ", ":").Split(":").Trim()[1]
?

**Comment by NickolajA** [comment]
Good catch, copy paste can be a ***** sometimes. Fixed in 2.2.3. Thanks
