### ISSUE TITLE
Surface Pro  1796 

### ISSUE THREAD

**Issue by darthsinus** [SCConfigMgr/ConfigMgr#8]
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1575625/ApplyDriverPackage.log)

When Building a Surface Pro 1796 from SCCM the script fails as it returns empty whilst looking for applicable driver packs.

The driver pack has been downloaded using the driver automation tool and appears to have the correct comment in the driver pack properties (Microsoft Surface Pro Windows 10 x64 Drivers (Models included:Surface_Pro_1796)), however it is skipped over by the script.

**Comment by NickolajA** [comment]
Could you try the latest version (2.0.0+) of the script to see if you have the same issue?

**Comment by darthsinus** [comment]
I tried again today but am getting the same behaviour. I used the latest version of the script and re-downloaded the driver pack with the latest version of the driver automation tool.

The error in the SMSTS log is: Failed to run the action: Dynamically Apply Drivers. 
The storage control block address is invalid. (Error: 00000009; Source: Windows). Which is due to returning n empty value when searching for the driver package I believe.

[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1638869/ApplyDriverPackage.log)

**Comment by NickolajA** [comment]
We had a small bug in version 2.0.0 that would not match the computer or SKU correctly. It has been fixed in 2.0.1. Could you give it a try?

**Comment by gvanngo** [comment]
I'l seeing this issue on script version 2.0.6.  Other models are working fine.  Any suggestions would be greatly appreciated.

**Comment by mdavis332** [comment]
Proposed a pull request #48 that may help with this (at least it fixed this same issue on the Dell Latitude E5530 non-vpro we had to test with).
