### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 - Issue with GetCMOSImageForTaskSequence and Source ISO

### ISSUE THREAD

**Issue by drlnz** [SCConfigMgr/ConfigMgr#81]
Error using version 2.1.5 of the Invoke-CMApplyDriverPackage.ps1 script with Webservice 1.6.0 and a Windows 10 (1803) ISO image - An error occured while calling ConfigMgr WebService to get OS Image data. Error message at line 361: Server was unable to process request. ---> Object reference not set to an instance of an object.

Calling the webservice directly has the same response - Exception calling "GetCMOSImageForTaskSequence" with "2" argument(s): "Server was unable to process request. ---> Object reference not set to an instance of an object."

This happens with the original source containing 10 indexes, as well as the same source with all but once index removed using DISM. 

If I switch to a captured 1803 image it works fine.

**Comment by NickolajA** [comment]
A fix for a similar issue was fixed after the release of ConfigMgr WebService 1.7.0. It'll be included in the upcoming version.
