### ISSUE TITLE
HP Prodesk 400 G4 Desktop mini PC issue with Invoke-CMdownloadBIOSpackage

### ISSUE THREAD

**Issue by peardvl** [SCConfigMgr/ConfigMgr#82]
Hi,
The error is:

Compare-BIOSVersion : Cannot convert value "02.02.04 A 1" to type "System.Version". Error: "Inndatastrengen hadde ugyldig format.	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)."	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)
At C:\_SMSTaskSequence\Packages\P0100D8E\Invoke-CMDownloadBIOSPackage.ps1:503 char:8	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)
+ ...             Compare-BIOSVersion -AvailableBIOSVersion $PackageList[0] ...	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)
    + CategoryInfo          : InvalidArgument: (:) [Compare-BIOSVersion], RuntimeException	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,Compare-BIOSVersion	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)
 	RunPowerShellScript	31.10.2018 13.35.16	9124 (0x23A4)

The error translated to english is: "data string has illegal format"

Anyone? Thanks.

**Comment by Schweinehund** [comment]
I got this to work by stripping off " A 1" off of the end of the version number on the BIOS package name.

**Comment by peardvl** [comment]
@Schweinehund Thank you very mutch. I will give it a try.

**Comment by peardvl** [comment]
@Schweinehund it works. Thank you.
