### ISSUE TITLE
Error w/ DISM when applying driver package: Missing .NET .dlls? 

### ISSUE THREAD

**Issue by sheriffharrytruman** [SCConfigMgr/ConfigMgr#83]
Step that runs DISM to import driver package fails. DISM.log shows errors 0x8007007e for MetaDeployProvider.dll and SiloedPackageProvider.dll. These files are not present in x:\windows\system32\dism.

I am able to locate SiloedPackageProvider.dll as part of the ADK but have no idea where I'm supposed to get MetaDeployProvider.dll

This is a new boot image with .NET included.

**Comment by sheriffharrytruman** [comment]
Will try adding WinPE-Dot3Svc to the boot WIM as an optional component.

**Comment by sheriffharrytruman** [comment]
Didn't fix the issue. Dism.log:  

[dism.log](https://github.com/SCConfigMgr/ConfigMgr/files/2559501/dism.log)

**Comment by sheriffharrytruman** [comment]
Also looks like the osd path c: isn't populating in the command line. Since I got everything else working, I'm just going to run DISM manually as a Run Command Line step after the script. Failing that, will add the download path to PathAndCredentials in unattend.xml.

**Comment by NickolajA** [comment]
Could you please provide more information as it's not really clear what the issue is here.

**Comment by Jrell** [comment]
> 
> 
> Also looks like the osd path c: isn't populating in the command line. Since I got everything else working, I'm just going to run DISM manually as a Run Command Line step after the script. Failing that, will add the download path to PathAndCredentials in unattend.xml.

did you manage to solve this? I am trying to inject a .ppkg file into a PE image during an OS deploy with DISM, but keep getting errors like you had.
