### ISSUE TITLE
Invoke-CMDownloadBIOSPackage.ps1 Issue with Lenovo ThinkPad X260

### ISSUE THREAD

**Issue by boozeman** [SCConfigMgr/ConfigMgr#84]
We have about 20 different Lenovo models and we are using Modern Bios Mgmt. There is a continuous error with Lenovo ThinkPad X260 (20F5),  while all other models work properly.

The script version is 2.0.6

Some smsts.log snip below

```
Parameter attributes need to be a constant or a script block.
At C:\WINDOWS\ccmcache\ib\Invoke-CMDownloadBIOSPackage.ps1:191 char:47
+             [ValidatePattern("^[A-Z0-9]{3}[A-F0-9]{5}$" <<<< )]
    + CategoryInfo          : ParserError: (:) [], ParseException  RunPowerShellScript
    + FullyQualifiedErrorId : ParameterAttributeArgumentNeedsToBeConstantOrScr
   iptBlock          
```

**Comment by boozeman** [comment]
This is not an issue at all! Machine needs at least WMF 4.0 for the scirpts working properly. This machine did not get that deployment for the reasons unknown.

**Comment by vorlon77** [comment]
You can also change the " into ' for the script to work with older versions
of powershell. In general use single quotes for constants unless you need
variable expansion. Changing the quotes may allow it to work for you in
this case.

Allan.
