### ISSUE TITLE
Problem with Invoke-LenovoBIOSUpdate.ps1 and ApplyDriverPackage

### ISSUE THREAD

**Issue by Takechico** [SCConfigMgr/ConfigMgr#88]
Hello!
I have a problem when try to update the BIOS and Applying drivers. Packages successfully download, but when it updates I have the following errors : Supported upgrade utility was not found (  for BIOS)  and Dism 87 error with drivers.
This is logs :
[ApplyBIOSPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2588796/ApplyBIOSPackage.log)

[Invoke-LenovoBIOSUpdate.log](https://github.com/SCConfigMgr/ConfigMgr/files/2588800/Invoke-LenovoBIOSUpdate.log)
For the BIOS At the TS i have this parametrs : powershell.exe -ExecutionPolicy Bypass -File Invoke-LenovoBIOSUpdate.ps1 -Path %OSDBIOSPackage01%   -LogFileName LenovoBIOSUpdate.log

[dism.log](https://github.com/SCConfigMgr/ConfigMgr/files/2588969/dism.log)
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/2588973/ApplyDriverPackage.log)

And for Drivers : powershell.exe -ExecutionPolicy Bypass -File Invoke-CMApplyDriverPackage.ps1 -URI http://myserver/ConfigMgrWebService/ConfigMgr.asmx -SecretKey d35d0973-0f3b-4301-b117-50d8ae6a0c03  -Filter Drivers

Could you help me?

**Comment by NickolajA** [comment]
Could you please test with the latest Invoke-LenovoBIOSUpdate.ps1 script as it has been recently updated.
