### ISSUE TITLE
Modern BIOS Management not working with HP ZBook G4

### ISSUE THREAD

**Issue by leinad13** [SCConfigMgr/ConfigMgr#9]
I'm trying to get the Modern BIOS Management solution working with HP models and came across an issue. I downloaded the BIOS package using the Driver Managment Tool. Its Package Details are : 

- Name : BIOS Update - HP ZBook 15 G4
- Version : 01.13
- Manufacturer : HP
- Language : English
- Comment : HP ZBook 15 G4 BIOS (Models included:8275)

The web service is all up and running (I have drivers working) and I can see in the log that 6 BIOS packages were returned by the web query but the applicable package isn't being matched.

`Package does not meet computer model and manufacturer criteria: BIOS Update - HP ZBook 15 G4 (PS100036)`

I think it's because the script sets the $ComputerManufacturer variable to 'Hewlett-Packard' for 'HP' machines then in the matching logic, the Package Manufacturer (HP) doesn't match. Changing the Manufacturer field in the package to 'Hewlett-Packard' solves the issue but it could probably be solved in the powershell script.

**Comment by viriio** [comment]
Any log files to share? e.g. BIOSPackageDownload.log
That'd help work out what its detecting and sending and help with where its exactly failing.

**Comment by leinad13** [comment]
Thanks viriio, i think that i have worked out the issue as explained above. Changing the Manufacturer field in the SCCM package to Hewlett-Packard resolves the issue. 

The switch statement at line 289 of the now renamed file - "Invoke-CMDownloadBIOSPackage-Old.ps1" changes the $ComputerManufacturer from 'HP' to 'Hewlett-Packard' and the manufacturer field in the SCCM package is "HP". If you change the manufacturer field to "Hewlett-Packard" in the SCCM package, the detection works.

The rest of the script works on the assumption that the manufacturer name for "HP" and "Hewlett-Packard" is always "Hewlett-Packard" so a number of changes are needed to resolve the issue.
