### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 - PowerShell.exe does not exist

### ISSUE THREAD

**Issue by rraschke** [SCConfigMgr/ConfigMgr#90]
Hi,

I have a problem when deployeing the "Invoke-CMApplyDriverPackage" script during a task sequence.
The screenshot below is from the "smsts.log".
![image](https://user-images.githubusercontent.com/40234312/49439346-13ef5180-f7c1-11e8-8b6e-2ed049683975.png)

This is my configuration of the task sequence:
![image](https://user-images.githubusercontent.com/40234312/49439433-400ad280-f7c1-11e8-8a64-9ed5da341334.png)

I have tried different positions in the TS during the "Install Operatin System" block, I always get the same message in the logfile.

Any ideas would be appreciated.

Robert

**Comment by WayneDinning** [comment]
Please check you have added Powershell support to your boot.wim?

**Comment by rraschke** [comment]
Thanks for this tip. I did not know, this was necessary. I will try that.
