### ISSUE TITLE
Driver Automation Tool version - 6.1.3 - Lenovo driver download path

### ISSUE THREAD

**Issue by HeyJudeRW** [SCConfigMgr/ConfigMgr#92]
There's an issue with the download paths for Lenovo drivers. The output of the script, when trying to DL drivers is:
ValidateProxyAccess : Cannot validate argument on parameter 'URL'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At D:\install.sys\configmgr\DriverAutomationTool\DriverAutomationTool.ps1:722 char:127
+ ... serName $ProxyUserInput.Text -Password $ProxyPswdInput.Text -URL $URL
+                                                                      ~~~~
    + CategoryInfo          : InvalidData: (:) [ValidateProxyAccess], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,ValidateProxyAccess

Get-Item : Cannot find path '\\KASEISCCM0003.dm-e.int\download$\Lenovo\ThinkPad T480\Driver Cab\54 55 56 57 ' because
it does not exist.
At D:\install.sys\configmgr\DriverAutomationTool\DriverAutomationTool.ps1:13076 char:87
+ ... e size:  $((Get-Item -Path $($DownloadRoot + $Model + '\Driver Cab\'  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\KASEISCCM0003...ab\54 55 56 57 :String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

Get-Item : Cannot find path '\\KASEISCCM0003.dm-e.int\download$\Lenovo\ThinkPad T470\Driver Cab\86 87 88 89 ' because
it does not exist.
At D:\install.sys\configmgr\DriverAutomationTool\DriverAutomationTool.ps1:13076 char:87
+ ... e size:  $((Get-Item -Path $($DownloadRoot + $Model + '\Driver Cab\'  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\KASEISCCM0003...ab\86 87 88 89 :String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

Get-Item : Cannot find path '\\KASEISCCM0003.dm-e.int\download$\Lenovo\ThinkPad X1 Carbon 3rd\Driver Cab\118 119 120
121 ' because it does not exist.
At D:\install.sys\configmgr\DriverAutomationTool\DriverAutomationTool.ps1:13076 char:87
+ ... e size:  $((Get-Item -Path $($DownloadRoot + $Model + '\Driver Cab\'  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\KASEISCCM0003...18 119 120 121 :String) [Get-Item], ItemNotFoundExcep
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

**Comment by maurice-daly** [comment]
Issue resolved in latest release.
