### ISSUE TITLE
Incorrect Driver Download Issue - HP 850 G5

### ISSUE THREAD

**Issue by vinitpandey01** [SCConfigMgr/ConfigMgr#96]
We have 840 G5 and 850 G5 in environment. Both have same SKU so driver package list gets two entries. When it tries to check using model name, it only matches with 840 and exits. It finally goes to match latest creation date, effectively getting 840 package. I know that ideally it should have matched both model and get 850, but only checking one of them.  I have tried to change name of driver package as model but it not working either. Please help. Here are logs:

<![LOG[Unable to match computer model using detection method: SystemSKU (83B2)]LOG]!><time="16:11:05.864+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="2" thread="2140" file="">
<![LOG[Driver package does not meet computer model, manufacturer and operating system and architecture criteria: Drivers - Hewlett-Packard Z6 G4 Workstation - Windows 10 1803 x64 (SVG0005D)]LOG]!><time="16:11:05.879+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="2" thread="2140" file="">

Here are the entries:

<![LOG[Driver package list contains 2 matches. Attempting to remove driver packages that do not match the computer model.]LOG]!><time="16:11:05.911+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Detected that the following driver package did not match the computer model: Drivers - Hewlett-Packard EliteBook 840 G5 Notebook PC - Windows 10 1803 x64]LOG]!><time="16:11:05.942+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Removing driver package due to inconsistency between computer model value from WMI 'HP EliteBook 850 G5' and the translated driver package computer model name 'HP EliteBook 840 G5 Notebook PC']LOG]!><time="16:11:05.973+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Driver package list contains multiple matches, attempting to download driver package content based upon latest package creation date]LOG]!><time="16:11:06.004+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Vendor specific matching required before downloading content. Attempting to match Hewlett-Packard driver package based on OS build number: 1803]LOG]!><time="16:11:06.020+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Attempting to download driver package SVG00057 content from Distribution Point]LOG]!><time="16:11:06.129+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDownloadPackages to: SVG00057]LOG]!><time="16:11:06.207+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDestinationLocationType to: Custom]LOG]!><time="16:11:06.254+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDestinationVariable to: OSDDriverPackage]LOG]!><time="16:11:06.270+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDestinationPath to: %_SMSTSMDataPath%\DriverPackage]LOG]!><time="16:11:06.287+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Starting package content download process, this might take some time]LOG]!><time="16:11:06.303+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Starting package content download process (WinPE), this might take some time]LOG]!><time="16:11:06.334+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Successfully downloaded package content with PackageID: SVG00057]LOG]!><time="16:14:26.823+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Driver package content downloaded successfully, attempting to apply drivers using dism.exe located in: C:\_SMSTaskSequence\DriverPackage\SVG00057]LOG]!><time="16:14:26.933+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Successfully applied drivers using dism.exe]LOG]!><time="16:16:17.927+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDownloadPackages to a blank value]LOG]!><time="16:16:17.944+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDestinationLocationType to a blank value]LOG]!><time="16:16:17.944+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDestinationVariable to a blank value]LOG]!><time="16:16:17.960+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">
<![LOG[Setting task sequence variable OSDDownloadDestinationPath to a blank value]LOG]!><time="16:16:17.975+-480" date="01-03-2019" component="ApplyDriverPackage" context="NT AUTHORITY\SYSTEM" type="1" thread="2140" file="">

**Comment by edr1986** [comment]
Hi, sort of the same issue here. SystemSKU matches 4 drivers packs. When it removes driver packs by checking model, it removes 3 driver packs, so 1 is still matched. But then it says multiple matches and selects the newest one.
