### ISSUE TITLE
Call to ConfigMgr WebService returned empty OS Image data (Stand Alone Media Only)

### ISSUE THREAD

**Issue by Azzaro78** [SCConfigMgr/ConfigMgr#99]
Hi,

First of all thank you for these god sent gifts that we are allowed to use! 

I'm having issue when using a working TS (Windows 10 X64 this case) where it works perfectly using the network boot.

But using that same TS exported to a Standalone Media it bugs out searching for the OS Image data.
Typical Error 4 but this is the log itself:

===== SCConfigMgr Invoke-CMApplyDriverPackage Version 2.1.5 ====		1/01/1601 0:00:00	0 (0x0000)
Driver download package process initiated		1/01/1601 0:00:00	0 (0x0000)
Manufacturer determined as: Dell		1/01/1601 0:00:00	0 (0x0000)
Computer model determined as: OptiPlex 3040		1/01/1601 0:00:00	0 (0x0000)
Computer SKU determined as: 06BB		1/01/1601 0:00:00	0 (0x0000)
Fallback SKU determined as: 06BB		1/01/1601 0:00:00	0 (0x0000)
Retrieved a total of 54 driver packages from web service		1/01/1601 0:00:00	0 (0x0000)
**Attempting to detect OS Image data from task sequence, running in DeploymentType: BareMetal**		1/01/1601 0:00:00	0 (0x0000)
**Call to ConfigMgr WebService returned empty OS Image data. Error message at line :** 		1/01/1601 0:00:00	0 (0x0000)

Is there a way to let the TS know what OS image is used and what architecture? 
Only 1 Apply Operating System task is used.

The image is applied but no drivers got installed (and so not domain joined etc).

Any help will be much appreciated!

**Comment by ecolint** [comment]
Hi,

I have the same problem and please see my post:
https://github.com/SCConfigMgr/ConfigMgr/issues/98

I still have no solution.

**Comment by NickolajA** [comment]
Stand-alone media where all the required content is staged within the media is not a supported scenario unfortunately, as we rely on the OSDDownloadContent.exe that will retrieve the driver package from a DP. We currently don't have any intentions of supporting this scenario, as we don't have a way of dynamically including the driver package content within the stand-alone media.
